import { defineRestConnector, apiKeyAuth, basicAuth } from '../factory'

// Communication connectors — Intercom, Mailchimp, Postmark, Vonage, WhatsApp Business.

export const intercomManifest = defineRestConnector({
  slug: 'intercom',
  name: 'Intercom',
  category: 'Communication',
  description: 'Conversations, contacts, and replies via the Intercom API.',
  baseUrl: 'https://api.intercom.io',
  headers: c => ({ Authorization: `Bearer ${c.api_key}`, 'Intercom-Version': '2.11' }),
  auth: apiKeyAuth({ service: 'Intercom', keyLabel: 'Access token', where: 'Settings → Integrations → Developer Hub → Your app → Authentication' }),
  testPath: '/me',
  testLabel: 'Intercom workspace connected',
  actions: [
    { slug: 'list_conversations', name: 'List conversations', risk: 'read', path: '/conversations', staticQuery: { per_page: '20' },
      description: 'Recent conversations with state and assignee.', params: {} },
    { slug: 'get_conversation', name: 'Get conversation', risk: 'read', path: '/conversations/{conversation_id}',
      description: 'One conversation including its message parts.',
      params: { conversation_id: { description: 'Conversation ID', required: true } } },
    { slug: 'search_contacts', name: 'Search contacts by email', risk: 'read', method: 'POST', path: '/contacts/search',
      description: 'Finds contacts with an exact email.',
      wrapBody: b => ({ query: { field: 'email', operator: '=', value: b.email } }),
      params: { email: { description: 'Email to search for', required: true } } },
    { slug: 'list_contacts', name: 'List contacts', risk: 'read', path: '/contacts', staticQuery: { per_page: '25' },
      description: 'Contacts (users and leads).', params: {} },
    { slug: 'create_contact', name: 'Create contact', risk: 'write', method: 'POST', path: '/contacts',
      description: 'Creates a user contact by email.',
      wrapBody: b => ({ role: 'user', email: b.email, ...(b.name ? { name: b.name } : {}) }),
      params: { email: { description: 'Email address', required: true }, name: { description: 'Full name (optional)' } } },
    { slug: 'reply_to_conversation', name: 'Reply to conversation', risk: 'write', method: 'POST', path: '/conversations/{conversation_id}/reply',
      description: 'Sends an admin reply. Get admin_id from list_admins.',
      wrapBody: b => ({ message_type: 'comment', type: 'admin', admin_id: String(b.admin_id), body: b.body }),
      params: { conversation_id: { description: 'Conversation ID', required: true }, admin_id: { description: 'Replying admin ID', required: true }, body: { description: 'Reply text', required: true } } },
    { slug: 'list_admins', name: 'List admins', risk: 'read', path: '/admins',
      description: 'Teammates (admins) with IDs — needed to reply.', params: {} },
  ],
})

export const mailchimpManifest = defineRestConnector({
  slug: 'mailchimp',
  name: 'Mailchimp',
  category: 'Communication',
  description: 'Audiences, subscribers, and campaign reports via the Mailchimp API.',
  baseUrl: c => `https://${(c.api_key.split('-')[1] || 'us1')}.api.mailchimp.com/3.0`,
  headers: c => ({ Authorization: basicAuth('anystring', c.api_key) }),
  auth: apiKeyAuth({ service: 'Mailchimp', keyLabel: 'API key', keyPlaceholder: 'xxxxxxxx-us21', where: 'Account → Extras → API keys', keyHint: 'The key ends with your data center (e.g. -us21) — paste the whole thing.' }),
  testPath: '/ping',
  testLabel: 'Mailchimp account connected',
  network: { hostPattern: '<your-datacentre>.api.mailchimp.com' },
  actions: [
    { slug: 'list_audiences', name: 'List audiences', risk: 'read', path: '/lists', staticQuery: { count: '20' },
      description: 'Your audiences (lists) with member counts.', params: {} },
    { slug: 'list_members', name: 'List audience members', risk: 'read', path: '/lists/{list_id}/members', staticQuery: { count: '30' },
      description: 'Subscribers in an audience. status: subscribed | unsubscribed | cleaned (optional).',
      params: { list_id: { description: 'Audience/list ID', required: true }, status: { description: 'Filter by status (optional)', enum: ['subscribed', 'unsubscribed', 'cleaned', 'pending'] } } },
    { slug: 'add_member', name: 'Add subscriber', risk: 'write', method: 'POST', path: '/lists/{list_id}/members',
      description: 'Subscribes an email to an audience.',
      wrapBody: b => ({ email_address: b.email, status: 'subscribed', ...(b.first_name || b.last_name ? { merge_fields: { FNAME: b.first_name ?? '', LNAME: b.last_name ?? '' } } : {}) }),
      params: { list_id: { description: 'Audience ID', required: true }, email: { description: 'Email address', required: true }, first_name: { description: 'First name (optional)' }, last_name: { description: 'Last name (optional)' } } },
    { slug: 'list_campaigns', name: 'List campaigns', risk: 'read', path: '/campaigns', staticQuery: { count: '20', sort_field: 'send_time', sort_dir: 'DESC' },
      description: 'Recent campaigns with status and send time.', params: {} },
    { slug: 'get_campaign_report', name: 'Get campaign report', risk: 'read', path: '/reports/{campaign_id}',
      description: 'Opens, clicks, and unsubscribes for a sent campaign.',
      params: { campaign_id: { description: 'Campaign ID', required: true } } },
  ],
})

export const postmarkManifest = defineRestConnector({
  slug: 'postmark',
  name: 'Postmark',
  category: 'Communication',
  description: 'Transactional email — send, track, and inspect bounces via the Postmark API.',
  baseUrl: 'https://api.postmarkapp.com',
  headers: c => ({ 'X-Postmark-Server-Token': c.api_key }),
  auth: apiKeyAuth({ service: 'Postmark', keyLabel: 'Server API token', where: 'Servers → your server → API Tokens' }),
  testPath: '/server',
  testLabel: 'Postmark server connected',
  actions: [
    { slug: 'send_email', name: 'Send email', risk: 'write', method: 'POST', path: '/email',
      description: 'Sends a plain-text email. From must be a verified sender signature.',
      wrapBody: b => ({ From: b.from, To: b.to, Subject: b.subject, TextBody: b.body }),
      params: { from: { description: 'Verified sender address', required: true }, to: { description: 'Recipient', required: true }, subject: { description: 'Subject', required: true }, body: { description: 'Plain-text body', required: true } } },
    { slug: 'list_outbound_messages', name: 'List sent messages', risk: 'read', path: '/messages/outbound', staticQuery: { count: '25', offset: '0' },
      description: 'Recently sent messages with delivery status.', params: {} },
    { slug: 'get_outbound_stats', name: 'Get send stats', risk: 'read', path: '/stats/outbound',
      description: 'Sent/bounced/opened totals for the server.', params: {} },
    { slug: 'list_bounces', name: 'List bounces', risk: 'read', path: '/bounces', staticQuery: { count: '25', offset: '0' },
      description: 'Recent bounces with reasons.', params: {} },
    { slug: 'list_templates', name: 'List templates', risk: 'read', path: '/templates', staticQuery: { Count: '30', Offset: '0' },
      description: 'Email templates on this server.', params: {} },
  ],
})

export const vonageManifest = defineRestConnector({
  slug: 'vonage',
  name: 'Vonage (Nexmo)',
  category: 'Communication',
  description: 'SMS and WhatsApp messaging via the Vonage Messages API.',
  baseUrl: 'https://api.nexmo.com',
  headers: c => ({ Authorization: basicAuth(c.key, c.secret) }),
  auth: {
    ...apiKeyAuth({ service: 'Vonage', where: 'dashboard.nexmo.com → API settings' }),
    fields: [
      { key: 'key', label: 'API key', placeholder: 'Your Vonage API key', inputType: 'text' },
      { key: 'secret', label: 'API secret', placeholder: 'Your Vonage API secret' },
    ],
  },
  testPath: '/v2/applications?page_size=1',
  testLabel: 'Vonage account connected',
  actions: [
    { slug: 'send_sms', name: 'Send SMS', risk: 'write', method: 'POST', path: '/v1/messages',
      description: 'Sends an SMS. Numbers in E.164 (+15551234567). Confirm with the user before sending.',
      wrapBody: b => ({ message_type: 'text', channel: 'sms', to: b.to, from: b.from, text: b.text }),
      params: { to: { description: 'Recipient number (E.164)', required: true }, from: { description: 'Your Vonage number or sender ID', required: true }, text: { description: 'Message text', required: true } } },
    { slug: 'send_whatsapp', name: 'Send WhatsApp message', risk: 'write', method: 'POST', path: '/v1/messages',
      description: 'Sends a WhatsApp text message via your Vonage WhatsApp number.',
      wrapBody: b => ({ message_type: 'text', channel: 'whatsapp', to: b.to, from: b.from, text: b.text }),
      params: { to: { description: 'Recipient number (E.164)', required: true }, from: { description: 'Your WhatsApp business number', required: true }, text: { description: 'Message text', required: true } } },
    { slug: 'list_applications', name: 'List applications', risk: 'read', path: '/v2/applications',
      description: 'Vonage applications on the account.', params: {} },
  ],
})

export const whatsappBusinessManifest = defineRestConnector({
  slug: 'whatsapp-business',
  name: 'WhatsApp Business',
  category: 'Communication',
  description: 'Send messages and manage templates via the WhatsApp Business Cloud API.',
  baseUrl: 'https://graph.facebook.com/v19.0',
  headers: c => ({ Authorization: `Bearer ${c.access_token}` }),
  auth: {
    ...apiKeyAuth({ service: 'WhatsApp Business', where: 'developers.facebook.com → your app → WhatsApp → API Setup' }),
    fields: [
      { key: 'access_token', label: 'Access token', placeholder: 'Your Meta access token' },
      { key: 'phone_number_id', label: 'Phone number ID', placeholder: 'From WhatsApp → API Setup', inputType: 'text' },
      { key: 'waba_id', label: 'Business account ID', placeholder: 'WhatsApp Business Account ID', inputType: 'text' },
    ],
  },
  testPath: '/me',
  testLabel: 'WhatsApp Business connected',
  actions: [
    { slug: 'send_message', name: 'Send text message', risk: 'write', method: 'POST', path: '/{phone_number_id}/messages',
      description: 'Sends a WhatsApp text (only within the 24h customer service window). Confirm with the user before sending.',
      wrapBody: b => ({ messaging_product: 'whatsapp', to: b.to, type: 'text', text: { body: b.text } }),
      params: { phone_number_id: { description: 'Your phone number ID', required: true }, to: { description: 'Recipient number (E.164, digits only)', required: true }, text: { description: 'Message text', required: true } } },
    { slug: 'send_template', name: 'Send template message', risk: 'write', method: 'POST', path: '/{phone_number_id}/messages',
      description: 'Sends an approved template (works outside the 24h window).',
      wrapBody: b => ({ messaging_product: 'whatsapp', to: b.to, type: 'template', template: { name: b.template_name, language: { code: b.language ?? 'en_US' } } }),
      params: { phone_number_id: { description: 'Your phone number ID', required: true }, to: { description: 'Recipient number', required: true }, template_name: { description: 'Approved template name', required: true }, language: { description: 'Language code (default en_US)' } } },
    { slug: 'list_templates', name: 'List message templates', risk: 'read', path: '/{waba_id}/message_templates',
      description: 'Approved and pending templates on the business account.',
      params: { waba_id: { description: 'WhatsApp Business Account ID', required: true } } },
    { slug: 'list_phone_numbers', name: 'List phone numbers', risk: 'read', path: '/{waba_id}/phone_numbers',
      description: 'Phone numbers on the business account.',
      params: { waba_id: { description: 'WhatsApp Business Account ID', required: true } } },
  ],
})

export const communicationConnectors = [
  intercomManifest, mailchimpManifest, postmarkManifest, vonageManifest, whatsappBusinessManifest,
]
