import { defineRestConnector, apiKeyAuth, basicAuth } from '../factory'

// CRM & Support connectors — HubSpot, Salesforce, Pipedrive, Freshdesk,
// Help Scout, Monday.com, Zoho CRM.

export const hubspotManifest = defineRestConnector({
  slug: 'hubspot',
  name: 'HubSpot',
  category: 'CRM & Support',
  description: 'Contacts, companies, deals, and tickets via the HubSpot CRM API.',
  baseUrl: 'https://api.hubapi.com',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'HubSpot', keyLabel: 'Private app token', keyPlaceholder: 'pat-…', where: 'Settings → Integrations → Private Apps' }),
  testPath: '/crm/v3/objects/contacts?limit=1',
  testLabel: 'HubSpot account connected',
  actions: [
    { slug: 'list_contacts', name: 'List contacts', risk: 'read', path: '/crm/v3/objects/contacts', staticQuery: { limit: '25', properties: 'email,firstname,lastname,company,lifecyclestage' },
      description: 'Contacts with email, name, and lifecycle stage.', params: {} },
    { slug: 'search_contacts', name: 'Search contacts', risk: 'read', method: 'POST', path: '/crm/v3/objects/contacts/search',
      description: 'Searches contacts by any text (name, email, company).',
      wrapBody: b => ({ query: b.query, limit: 20 }),
      params: { query: { description: 'Search text', required: true } } },
    { slug: 'create_contact', name: 'Create contact', risk: 'write', method: 'POST', path: '/crm/v3/objects/contacts',
      description: 'Creates a contact.',
      wrapBody: b => ({ properties: { email: b.email, firstname: b.firstname, lastname: b.lastname } }),
      params: { email: { description: 'Email address', required: true }, firstname: { description: 'First name' }, lastname: { description: 'Last name' } } },
    { slug: 'list_deals', name: 'List deals', risk: 'read', path: '/crm/v3/objects/deals', staticQuery: { limit: '25', properties: 'dealname,amount,dealstage,closedate,pipeline' },
      description: 'Deals with amount, stage, and close date.', params: {} },
    { slug: 'create_deal', name: 'Create deal', risk: 'write', method: 'POST', path: '/crm/v3/objects/deals',
      description: 'Creates a deal.',
      wrapBody: b => ({ properties: { dealname: b.name, amount: b.amount, dealstage: b.stage ?? 'appointmentscheduled' } }),
      params: { name: { description: 'Deal name', required: true }, amount: { type: 'number', description: 'Deal amount' }, stage: { description: 'Pipeline stage (optional)' } } },
    { slug: 'update_deal', name: 'Update deal', risk: 'write', method: 'PATCH', path: '/crm/v3/objects/deals/{deal_id}',
      description: 'Updates deal properties (e.g. move stage). properties: object of property → value.',
      wrapBody: b => ({ properties: b.properties ?? {} }),
      params: { deal_id: { description: 'Deal ID', required: true }, properties: { type: 'object', description: 'e.g. {"dealstage":"closedwon"}', required: true } } },
    { slug: 'list_companies', name: 'List companies', risk: 'read', path: '/crm/v3/objects/companies', staticQuery: { limit: '25', properties: 'name,domain,industry,numberofemployees' },
      description: 'Companies with domain and industry.', params: {} },
    { slug: 'list_tickets', name: 'List tickets', risk: 'read', path: '/crm/v3/objects/tickets', staticQuery: { limit: '25', properties: 'subject,content,hs_pipeline_stage,hs_ticket_priority' },
      description: 'Support tickets with stage and priority.', params: {} },
  ],
})

export const salesforceManifest = defineRestConnector({
  slug: 'salesforce',
  name: 'Salesforce',
  category: 'CRM & Support',
  description: 'SOQL queries, leads, opportunities, and record CRUD via the Salesforce REST API.',
  baseUrl: c => c.instance_url,
  headers: c => ({ Authorization: `Bearer ${c.access_token}` }),
  auth: {
    ...apiKeyAuth({ service: 'Salesforce', where: 'Setup → Apps → Connected Apps (OAuth token)' }),
    fields: [
      { key: 'instance_url', label: 'Instance URL', placeholder: 'https://yourorg.my.salesforce.com', inputType: 'text' },
      { key: 'access_token', label: 'OAuth access token', placeholder: 'Your Salesforce session token', hint: 'Advanced — most people should use Simulate mode.' },
    ],
  },
  testPath: '/services/data/v59.0/limits',
  testLabel: 'Salesforce org connected',
  network: { customerHost: true },
  actions: [
    { slug: 'soql_query', name: 'Run SOQL query', risk: 'read', path: '/services/data/v59.0/query',
      description: 'Runs a SOQL query, e.g. "SELECT Id, Name, Amount FROM Opportunity WHERE IsClosed = false LIMIT 25".',
      params: { q: { description: 'SOQL query', required: true } } },
    { slug: 'list_opportunities', name: 'List open opportunities', risk: 'read', path: '/services/data/v59.0/query',
      staticQuery: { q: 'SELECT Id, Name, Amount, StageName, CloseDate, Account.Name FROM Opportunity WHERE IsClosed = false ORDER BY CloseDate LIMIT 50' },
      description: 'Open opportunities with amount, stage, and close date.', params: {} },
    { slug: 'list_leads', name: 'List recent leads', risk: 'read', path: '/services/data/v59.0/query',
      staticQuery: { q: 'SELECT Id, Name, Company, Email, Status, CreatedDate FROM Lead ORDER BY CreatedDate DESC LIMIT 50' },
      description: 'Most recent leads.', params: {} },
    { slug: 'get_record', name: 'Get record', risk: 'read', path: '/services/data/v59.0/sobjects/{object}/{record_id}',
      description: 'One record by object type and ID.',
      params: { object: { description: 'Object type, e.g. Account, Contact, Opportunity', required: true }, record_id: { description: 'Record ID', required: true } } },
    { slug: 'create_record', name: 'Create record', risk: 'write', method: 'POST', path: '/services/data/v59.0/sobjects/{object}',
      description: 'Creates a record. fields: object of field → value, e.g. {"LastName":"Smith","Company":"Acme"}.',
      wrapBody: b => (b.fields ?? {}) as Record<string, unknown>,
      params: { object: { description: 'Object type, e.g. Lead', required: true }, fields: { type: 'object', description: 'Field values', required: true } } },
    { slug: 'update_record', name: 'Update record', risk: 'write', method: 'PATCH', path: '/services/data/v59.0/sobjects/{object}/{record_id}',
      description: 'Updates fields on a record.',
      wrapBody: b => (b.fields ?? {}) as Record<string, unknown>,
      params: { object: { description: 'Object type', required: true }, record_id: { description: 'Record ID', required: true }, fields: { type: 'object', description: 'Field values to change', required: true } } },
  ],
})

export const pipedriveManifest = defineRestConnector({
  slug: 'pipedrive',
  name: 'Pipedrive',
  category: 'CRM & Support',
  description: 'Deals, people, activities, and notes via the Pipedrive API.',
  baseUrl: c => `https://${c.company_domain}.pipedrive.com/api/v1`,
  headers: c => ({ 'x-api-token': c.api_key }),
  auth: {
    ...apiKeyAuth({ service: 'Pipedrive', where: 'Settings → Personal preferences → API' }),
    fields: [
      { key: 'company_domain', label: 'Company domain', placeholder: 'yourcompany (from yourcompany.pipedrive.com)', inputType: 'text' },
      { key: 'api_key', label: 'API token', placeholder: 'Your Pipedrive API token' },
    ],
  },
  testPath: '/users/me',
  testLabel: 'Pipedrive account connected',
  network: { hostPattern: '<your-company>.pipedrive.com' },
  actions: [
    { slug: 'list_deals', name: 'List deals', risk: 'read', path: '/deals', staticQuery: { limit: '50' },
      description: 'Deals with value, stage, and status. status: open | won | lost | all_not_deleted.',
      params: { status: { description: 'Filter by status (optional)', enum: ['open', 'won', 'lost', 'all_not_deleted'] } } },
    { slug: 'get_deal', name: 'Get deal', risk: 'read', path: '/deals/{deal_id}',
      description: 'One deal with full details.',
      params: { deal_id: { type: 'integer', description: 'Deal ID', required: true } } },
    { slug: 'create_deal', name: 'Create deal', risk: 'write', method: 'POST', path: '/deals',
      description: 'Creates a deal.',
      params: { title: { description: 'Deal title', required: true }, value: { type: 'number', description: 'Deal value' }, person_id: { type: 'integer', description: 'Linked person ID (optional)' } } },
    { slug: 'update_deal', name: 'Update deal', risk: 'write', method: 'PUT', path: '/deals/{deal_id}',
      description: 'Updates a deal (e.g. stage_id, status won/lost).',
      params: { deal_id: { type: 'integer', description: 'Deal ID', required: true }, status: { description: 'open | won | lost (optional)' }, stage_id: { type: 'integer', description: 'Move to stage (optional)' } } },
    { slug: 'list_persons', name: 'List people', risk: 'read', path: '/persons', staticQuery: { limit: '50' },
      description: 'Contacts with email and organization.', params: {} },
    { slug: 'create_person', name: 'Create person', risk: 'write', method: 'POST', path: '/persons',
      description: 'Creates a contact.',
      params: { name: { description: 'Full name', required: true }, email: { description: 'Email (optional)' }, phone: { description: 'Phone (optional)' } } },
    { slug: 'list_activities', name: 'List activities', risk: 'read', path: '/activities', staticQuery: { limit: '50' },
      description: 'Tasks/calls/meetings with due dates and done status.', params: {} },
    { slug: 'add_note', name: 'Add note to deal', risk: 'write', method: 'POST', path: '/notes',
      description: 'Attaches a note to a deal.',
      params: { deal_id: { type: 'integer', description: 'Deal ID', required: true }, content: { description: 'Note text', required: true } } },
  ],
})

export const freshdeskManifest = defineRestConnector({
  slug: 'freshdesk',
  name: 'Freshdesk',
  category: 'CRM & Support',
  description: 'Tickets, replies, and contacts via the Freshdesk API.',
  baseUrl: c => `https://${c.domain}.freshdesk.com/api/v2`,
  headers: c => ({ Authorization: basicAuth(c.api_key, 'X') }),
  auth: {
    ...apiKeyAuth({ service: 'Freshdesk', where: 'Profile Settings → View API Key' }),
    fields: [
      { key: 'domain', label: 'Freshdesk domain', placeholder: 'yourcompany (from yourcompany.freshdesk.com)', inputType: 'text' },
      { key: 'api_key', label: 'API key', placeholder: 'Your Freshdesk API key' },
    ],
  },
  testPath: '/tickets?per_page=1',
  testLabel: 'Freshdesk account connected',
  network: { hostPattern: '<your-domain>.freshdesk.com' },
  actions: [
    { slug: 'list_tickets', name: 'List tickets', risk: 'read', path: '/tickets', staticQuery: { per_page: '30' },
      description: 'Tickets, newest first, with status and priority.', params: {} },
    { slug: 'get_ticket', name: 'Get ticket', risk: 'read', path: '/tickets/{ticket_id}', staticQuery: { include: 'conversations' },
      description: 'One ticket including its conversation.',
      params: { ticket_id: { type: 'integer', description: 'Ticket ID', required: true } } },
    { slug: 'create_ticket', name: 'Create ticket', risk: 'write', method: 'POST', path: '/tickets',
      description: 'Creates a ticket. priority 1–4 (low→urgent), status 2=open.',
      wrapBody: b => ({ subject: b.subject, description: b.description, email: b.email, priority: Number(b.priority ?? 1), status: 2 }),
      params: { subject: { description: 'Ticket subject', required: true }, description: { description: 'Ticket body', required: true }, email: { description: 'Requester email', required: true }, priority: { type: 'integer', description: '1 low – 4 urgent (default 1)' } } },
    { slug: 'reply_to_ticket', name: 'Reply to ticket', risk: 'write', method: 'POST', path: '/tickets/{ticket_id}/reply',
      description: 'Sends a public reply to the requester.',
      wrapBody: b => ({ body: b.body }),
      params: { ticket_id: { type: 'integer', description: 'Ticket ID', required: true }, body: { description: 'Reply text (HTML ok)', required: true } } },
    { slug: 'update_ticket', name: 'Update ticket', risk: 'write', method: 'PUT', path: '/tickets/{ticket_id}',
      description: 'Updates status/priority. status: 2 open, 3 pending, 4 resolved, 5 closed.',
      params: { ticket_id: { type: 'integer', description: 'Ticket ID', required: true }, status: { type: 'integer', description: '2 open | 3 pending | 4 resolved | 5 closed' }, priority: { type: 'integer', description: '1–4 (optional)' } } },
    { slug: 'list_contacts', name: 'List contacts', risk: 'read', path: '/contacts', staticQuery: { per_page: '30' },
      description: 'Requester contacts.', params: {} },
  ],
})

export const helpScoutManifest = defineRestConnector({
  slug: 'help-scout',
  name: 'Help Scout',
  category: 'CRM & Support',
  description: 'Mailboxes, conversations, and customers via the Help Scout API.',
  baseUrl: 'https://api.helpscout.net',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'Help Scout', keyLabel: 'OAuth access token', where: 'My Apps → Create App (client-credentials token)', keyHint: 'Advanced — most people should use Simulate mode.' }),
  testPath: '/v2/mailboxes',
  testLabel: 'Help Scout account connected',
  actions: [
    { slug: 'list_mailboxes', name: 'List mailboxes', risk: 'read', path: '/v2/mailboxes',
      description: 'Your Help Scout mailboxes.', params: {} },
    { slug: 'list_conversations', name: 'List conversations', risk: 'read', path: '/v2/conversations', staticQuery: { status: 'active', sortField: 'modifiedAt', sortOrder: 'desc' },
      description: 'Active conversations, most recently updated first.',
      params: { mailbox: { type: 'integer', description: 'Filter by mailbox ID (optional)' } } },
    { slug: 'get_conversation', name: 'Get conversation', risk: 'read', path: '/v2/conversations/{conversation_id}', staticQuery: { embed: 'threads' },
      description: 'One conversation including its message threads.',
      params: { conversation_id: { type: 'integer', description: 'Conversation ID', required: true } } },
    { slug: 'add_note', name: 'Add internal note', risk: 'write', method: 'POST', path: '/v2/conversations/{conversation_id}/notes',
      description: 'Adds a private note to a conversation (not sent to the customer).',
      wrapBody: b => ({ text: b.text }),
      params: { conversation_id: { type: 'integer', description: 'Conversation ID', required: true }, text: { description: 'Note text', required: true } } },
    { slug: 'list_customers', name: 'List customers', risk: 'read', path: '/v2/customers', staticQuery: { sortField: 'modifiedAt', sortOrder: 'desc' },
      description: 'Customers with contact details.', params: {} },
  ],
})

export const mondayManifest = defineRestConnector({
  slug: 'monday',
  name: 'Monday.com',
  category: 'CRM & Support',
  description: 'Boards, items, and status updates via the Monday.com GraphQL API.',
  baseUrl: 'https://api.monday.com',
  headers: c => ({ Authorization: c.api_key, 'API-Version': '2024-01' }),
  auth: apiKeyAuth({ service: 'Monday.com', keyLabel: 'API token', where: 'Avatar → Developers → My Access Tokens' }),
  testPath: '/v2',
  testInit: { method: 'POST', body: { query: '{ me { name } }' } },
  testLabel: 'Monday.com account connected',
  actions: [
    { slug: 'list_boards', name: 'List boards', risk: 'read', method: 'POST', path: '/v2',
      description: 'Your boards with IDs.',
      wrapBody: () => ({ query: '{ boards(limit: 30) { id name state items_count } }' }),
      params: {} },
    { slug: 'list_items', name: 'List items on board', risk: 'read', method: 'POST', path: '/v2',
      description: 'Items (rows) on a board with their column values.',
      wrapBody: b => ({ query: `{ boards(ids: [${Number(b.board_id)}]) { items_page(limit: 50) { items { id name column_values { id text } } } } }` }),
      params: { board_id: { type: 'integer', description: 'Board ID', required: true } } },
    { slug: 'create_item', name: 'Create item', risk: 'write', method: 'POST', path: '/v2',
      description: 'Adds an item (row) to a board.',
      wrapBody: b => ({ query: `mutation { create_item(board_id: ${Number(b.board_id)}, item_name: ${JSON.stringify(String(b.name ?? 'New item'))}) { id name } }` }),
      params: { board_id: { type: 'integer', description: 'Board ID', required: true }, name: { description: 'Item name', required: true } } },
    { slug: 'update_item_status', name: 'Update item status', risk: 'write', method: 'POST', path: '/v2',
      description: 'Sets a status column on an item, e.g. column "status" to "Done".',
      wrapBody: b => ({ query: `mutation { change_simple_column_value(board_id: ${Number(b.board_id)}, item_id: ${Number(b.item_id)}, column_id: ${JSON.stringify(String(b.column_id ?? 'status'))}, value: ${JSON.stringify(String(b.value ?? ''))}) { id } }` }),
      params: { board_id: { type: 'integer', description: 'Board ID', required: true }, item_id: { type: 'integer', description: 'Item ID', required: true }, column_id: { description: 'Column id (default "status")' }, value: { description: 'New value, e.g. "Done"', required: true } } },
  ],
})

export const zohoCrmManifest = defineRestConnector({
  slug: 'zoho-crm',
  name: 'Zoho CRM',
  category: 'CRM & Support',
  description: 'Leads, contacts, and deals via the Zoho CRM v5 API.',
  baseUrl: c => `https://www.zohoapis.${c.dc || 'com'}/crm/v5`,
  headers: c => ({ Authorization: `Zoho-oauthtoken ${c.access_token}` }),
  auth: {
    ...apiKeyAuth({ service: 'Zoho CRM', where: 'api-console.zoho.com (self-client OAuth token)' }),
    fields: [
      { key: 'access_token', label: 'OAuth access token', placeholder: 'Your Zoho OAuth token', hint: 'Advanced — most people should use Simulate mode.' },
      { key: 'dc', label: 'Data center (optional)', placeholder: 'com | eu | in — leave blank for .com', inputType: 'text' },
    ],
  },
  testPath: '/org',
  testLabel: 'Zoho CRM connected',
  network: { hostPattern: 'www.zohoapis.<your-datacentre>' },
  actions: [
    { slug: 'list_records', name: 'List records', risk: 'read', path: '/{module}', staticQuery: { per_page: '50' },
      description: 'Records from a module: Leads, Contacts, Deals, Accounts, Tasks.',
      params: { module: { description: 'Module name, e.g. Leads', required: true, enum: ['Leads', 'Contacts', 'Deals', 'Accounts', 'Tasks'] } } },
    { slug: 'search_records', name: 'Search records', risk: 'read', path: '/{module}/search',
      description: 'Searches a module by word.',
      params: { module: { description: 'Module name', required: true }, word: { description: 'Search text', required: true } } },
    { slug: 'create_record', name: 'Create record', risk: 'write', method: 'POST', path: '/{module}',
      description: 'Creates a record. fields: object of API field → value, e.g. {"Last_Name":"Smith","Company":"Acme"}.',
      wrapBody: b => ({ data: [b.fields ?? {}] }),
      params: { module: { description: 'Module name', required: true }, fields: { type: 'object', description: 'Field values', required: true } } },
    { slug: 'update_record', name: 'Update record', risk: 'write', method: 'PUT', path: '/{module}/{record_id}',
      description: 'Updates fields on a record.',
      wrapBody: b => ({ data: [b.fields ?? {}] }),
      params: { module: { description: 'Module name', required: true }, record_id: { description: 'Record ID', required: true }, fields: { type: 'object', description: 'Field values to change', required: true } } },
  ],
})

export const crmSupportConnectors = [
  hubspotManifest, salesforceManifest, pipedriveManifest, freshdeskManifest,
  helpScoutManifest, mondayManifest, zohoCrmManifest,
]
