import { defineRestConnector, apiKeyAuth, basicAuth } from '../factory'

// DevOps connectors — GitHub, GitLab, Jira, Confluence, CircleCI, Argo CD,
// Terraform Cloud. All plain REST via the factory; Simulate mode needs nothing.

export const githubManifest = defineRestConnector({
  slug: 'github',
  name: 'GitHub',
  category: 'DevOps',
  description: 'Repos, issues, pull requests, commits, and Actions runs via the GitHub REST API.',
  baseUrl: 'https://api.github.com',
  headers: c => ({ Authorization: `Bearer ${c.api_key}`, 'X-GitHub-Api-Version': '2022-11-28' }),
  auth: apiKeyAuth({ service: 'GitHub', keyLabel: 'Personal access token', keyPlaceholder: 'ghp_… or github_pat_…', where: 'Settings → Developer settings → Personal access tokens' }),
  testPath: '/user',
  testLabel: 'GitHub account connected',
  actions: [
    { slug: 'list_repos', name: 'List repositories', risk: 'read', path: '/user/repos', staticQuery: { per_page: '30', sort: 'updated' },
      description: 'Lists repositories the authenticated user can access, most recently updated first.', params: {} },
    { slug: 'search_repos', name: 'Search repositories', risk: 'read', path: '/search/repositories',
      description: 'Searches public repositories. q: GitHub search syntax, e.g. "topic:ai language:typescript".',
      params: { q: { description: 'Search query (GitHub search syntax)', required: true } } },
    { slug: 'list_issues', name: 'List issues', risk: 'read', path: '/repos/{owner}/{repo}/issues',
      description: 'Lists issues in a repo. state: open | closed | all (default open). Pull requests appear here too (they have a pull_request field).',
      params: { owner: { description: 'Repo owner (user or org)', required: true }, repo: { description: 'Repo name', required: true }, state: { description: 'open | closed | all', enum: ['open', 'closed', 'all'] } } },
    { slug: 'create_issue', name: 'Create issue', risk: 'write', method: 'POST', path: '/repos/{owner}/{repo}/issues',
      description: 'Opens a new issue. title required; body is markdown.',
      params: { owner: { description: 'Repo owner', required: true }, repo: { description: 'Repo name', required: true }, title: { description: 'Issue title', required: true }, body: { description: 'Issue body (markdown)' } } },
    { slug: 'comment_on_issue', name: 'Comment on issue', risk: 'write', method: 'POST', path: '/repos/{owner}/{repo}/issues/{issue_number}/comments',
      description: 'Adds a comment to an issue or pull request.',
      params: { owner: { description: 'Repo owner', required: true }, repo: { description: 'Repo name', required: true }, issue_number: { type: 'integer', description: 'Issue/PR number', required: true }, body: { description: 'Comment text (markdown)', required: true } } },
    { slug: 'close_issue', name: 'Close issue', risk: 'write', method: 'PATCH', path: '/repos/{owner}/{repo}/issues/{issue_number}',
      description: 'Closes an issue.', wrapBody: () => ({ state: 'closed' }),
      params: { owner: { description: 'Repo owner', required: true }, repo: { description: 'Repo name', required: true }, issue_number: { type: 'integer', description: 'Issue number', required: true } } },
    { slug: 'list_pull_requests', name: 'List pull requests', risk: 'read', path: '/repos/{owner}/{repo}/pulls',
      description: 'Lists pull requests. state: open | closed | all.',
      params: { owner: { description: 'Repo owner', required: true }, repo: { description: 'Repo name', required: true }, state: { description: 'open | closed | all', enum: ['open', 'closed', 'all'] } } },
    { slug: 'get_pull_request', name: 'Get pull request', risk: 'read', path: '/repos/{owner}/{repo}/pulls/{pull_number}',
      description: 'Full details of one pull request, including mergeability.',
      params: { owner: { description: 'Repo owner', required: true }, repo: { description: 'Repo name', required: true }, pull_number: { type: 'integer', description: 'PR number', required: true } } },
    { slug: 'merge_pull_request', name: 'Merge pull request', risk: 'destructive', method: 'PUT', path: '/repos/{owner}/{repo}/pulls/{pull_number}/merge',
      description: 'Merges a pull request. Irreversible — confirm before using.',
      params: { owner: { description: 'Repo owner', required: true }, repo: { description: 'Repo name', required: true }, pull_number: { type: 'integer', description: 'PR number', required: true } } },
    { slug: 'list_commits', name: 'List commits', risk: 'read', path: '/repos/{owner}/{repo}/commits', staticQuery: { per_page: '30' },
      description: 'Recent commits on the default branch (or sha/branch via the sha param).',
      params: { owner: { description: 'Repo owner', required: true }, repo: { description: 'Repo name', required: true }, sha: { description: 'Branch or commit SHA to start from (optional)' } } },
    { slug: 'list_workflow_runs', name: 'List Actions runs', risk: 'read', path: '/repos/{owner}/{repo}/actions/runs', staticQuery: { per_page: '20' },
      description: 'Recent GitHub Actions workflow runs with status and conclusion.',
      params: { owner: { description: 'Repo owner', required: true }, repo: { description: 'Repo name', required: true }, status: { description: 'Filter: completed | in_progress | queued (optional)' } } },
    { slug: 'list_branches', name: 'List branches', risk: 'read', path: '/repos/{owner}/{repo}/branches',
      description: 'Lists branches in a repo.',
      params: { owner: { description: 'Repo owner', required: true }, repo: { description: 'Repo name', required: true } } },
  ],
})

export const gitlabManifest = defineRestConnector({
  slug: 'gitlab',
  name: 'GitLab',
  category: 'DevOps',
  description: 'Projects, issues, merge requests, and CI pipelines via the GitLab REST API.',
  baseUrl: 'https://gitlab.com/api/v4',
  headers: c => ({ 'PRIVATE-TOKEN': c.api_key }),
  auth: apiKeyAuth({ service: 'GitLab', keyLabel: 'Personal access token', keyPlaceholder: 'glpat-…', where: 'User Settings → Access Tokens' }),
  testPath: '/user',
  testLabel: 'GitLab account connected',
  actions: [
    { slug: 'list_projects', name: 'List projects', risk: 'read', path: '/projects', staticQuery: { membership: 'true', per_page: '30', order_by: 'last_activity_at' },
      description: 'Projects you are a member of, most recently active first.', params: {} },
    { slug: 'list_issues', name: 'List issues', risk: 'read', path: '/projects/{project_id}/issues',
      description: 'Issues in a project. state: opened | closed | all.',
      params: { project_id: { type: 'integer', description: 'Numeric project ID', required: true }, state: { description: 'opened | closed | all', enum: ['opened', 'closed', 'all'] } } },
    { slug: 'create_issue', name: 'Create issue', risk: 'write', method: 'POST', path: '/projects/{project_id}/issues',
      description: 'Opens an issue in a project.',
      params: { project_id: { type: 'integer', description: 'Project ID', required: true }, title: { description: 'Issue title', required: true }, description: { description: 'Issue body (markdown)' } } },
    { slug: 'comment_on_issue', name: 'Comment on issue', risk: 'write', method: 'POST', path: '/projects/{project_id}/issues/{issue_iid}/notes',
      description: 'Adds a note (comment) to an issue.',
      params: { project_id: { type: 'integer', description: 'Project ID', required: true }, issue_iid: { type: 'integer', description: 'Issue IID (project-local number)', required: true }, body: { description: 'Comment text', required: true } } },
    { slug: 'close_issue', name: 'Close issue', risk: 'write', method: 'PUT', path: '/projects/{project_id}/issues/{issue_iid}', staticQuery: {},
      description: 'Closes an issue.', wrapBody: () => ({ state_event: 'close' }),
      params: { project_id: { type: 'integer', description: 'Project ID', required: true }, issue_iid: { type: 'integer', description: 'Issue IID', required: true } } },
    { slug: 'list_merge_requests', name: 'List merge requests', risk: 'read', path: '/projects/{project_id}/merge_requests',
      description: 'Merge requests in a project. state: opened | merged | closed | all.',
      params: { project_id: { type: 'integer', description: 'Project ID', required: true }, state: { description: 'opened | merged | closed | all', enum: ['opened', 'merged', 'closed', 'all'] } } },
    { slug: 'merge_merge_request', name: 'Merge a merge request', risk: 'destructive', method: 'PUT', path: '/projects/{project_id}/merge_requests/{mr_iid}/merge',
      description: 'Merges a merge request. Irreversible — confirm before using.',
      params: { project_id: { type: 'integer', description: 'Project ID', required: true }, mr_iid: { type: 'integer', description: 'MR IID', required: true } } },
    { slug: 'list_pipelines', name: 'List pipelines', risk: 'read', path: '/projects/{project_id}/pipelines', staticQuery: { per_page: '20' },
      description: 'Recent CI pipelines with status.',
      params: { project_id: { type: 'integer', description: 'Project ID', required: true }, status: { description: 'Filter: success | failed | running (optional)' } } },
    { slug: 'trigger_pipeline', name: 'Trigger pipeline', risk: 'write', method: 'POST', path: '/projects/{project_id}/pipeline',
      description: 'Starts a new CI pipeline on a ref (branch or tag).',
      params: { project_id: { type: 'integer', description: 'Project ID', required: true }, ref: { description: 'Branch or tag name', required: true } } },
    { slug: 'list_commits', name: 'List commits', risk: 'read', path: '/projects/{project_id}/repository/commits', staticQuery: { per_page: '30' },
      description: 'Recent commits. ref_name: branch (optional).',
      params: { project_id: { type: 'integer', description: 'Project ID', required: true }, ref_name: { description: 'Branch name (optional)' } } },
  ],
})

export const jiraManifest = defineRestConnector({
  slug: 'jira',
  name: 'Jira Software',
  category: 'DevOps',
  description: 'Issues, JQL search, transitions, boards, and sprints via the Jira Cloud REST API.',
  baseUrl: c => c.site,
  headers: c => ({ Authorization: basicAuth(c.email, c.api_token) }),
  auth: {
    ...apiKeyAuth({ service: 'Jira', where: 'id.atlassian.com → Security → API tokens' }),
    fields: [
      { key: 'site', label: 'Jira site', placeholder: 'yourcompany.atlassian.net', inputType: 'text', hint: 'The domain you open Jira at.' },
      { key: 'email', label: 'Account email', placeholder: 'you@company.com', inputType: 'text' },
      { key: 'api_token', label: 'API token', placeholder: 'Your Atlassian API token', hint: 'Create at id.atlassian.com → Security → API tokens.' },
    ],
  },
  testPath: '/rest/api/3/myself',
  testLabel: 'Jira site connected',
  network: { customerHost: true },
  actions: [
    { slug: 'search_issues', name: 'Search issues (JQL)', risk: 'read', path: '/rest/api/3/search', staticQuery: { maxResults: '30' },
      description: 'Searches issues with JQL, e.g. "project = OPS AND status = \'In Progress\' ORDER BY updated DESC".',
      params: { jql: { description: 'JQL query', required: true } } },
    { slug: 'get_issue', name: 'Get issue', risk: 'read', path: '/rest/api/3/issue/{issue_key}',
      description: 'Full details of one issue by key, e.g. OPS-123.',
      params: { issue_key: { description: 'Issue key, e.g. OPS-123', required: true } } },
    { slug: 'create_issue', name: 'Create issue', risk: 'write', method: 'POST', path: '/rest/api/3/issue',
      description: 'Creates an issue. issue_type: Task, Bug, Story, etc.',
      wrapBody: b => ({ fields: { project: { key: b.project_key }, summary: b.summary, issuetype: { name: b.issue_type ?? 'Task' }, ...(b.description ? { description: { type: 'doc', version: 1, content: [{ type: 'paragraph', content: [{ type: 'text', text: String(b.description) }] }] } } : {}) } }),
      params: { project_key: { description: 'Project key, e.g. OPS', required: true }, summary: { description: 'Issue title', required: true }, issue_type: { description: 'Task | Bug | Story (default Task)' }, description: { description: 'Issue description (plain text)' } } },
    { slug: 'add_comment', name: 'Add comment', risk: 'write', method: 'POST', path: '/rest/api/3/issue/{issue_key}/comment',
      description: 'Adds a comment to an issue.',
      wrapBody: b => ({ body: { type: 'doc', version: 1, content: [{ type: 'paragraph', content: [{ type: 'text', text: String(b.text ?? '') }] }] } }),
      params: { issue_key: { description: 'Issue key', required: true }, text: { description: 'Comment text', required: true } } },
    { slug: 'list_transitions', name: 'List transitions', risk: 'read', path: '/rest/api/3/issue/{issue_key}/transitions',
      description: 'Lists the workflow transitions currently available for an issue (use before transition_issue).',
      params: { issue_key: { description: 'Issue key', required: true } } },
    { slug: 'transition_issue', name: 'Transition issue', risk: 'write', method: 'POST', path: '/rest/api/3/issue/{issue_key}/transitions',
      description: 'Moves an issue through its workflow (e.g. to Done). Get transition_id from list_transitions first.',
      wrapBody: b => ({ transition: { id: String(b.transition_id) } }),
      params: { issue_key: { description: 'Issue key', required: true }, transition_id: { description: 'Transition ID from list_transitions', required: true } } },
    { slug: 'assign_issue', name: 'Assign issue', risk: 'write', method: 'PUT', path: '/rest/api/3/issue/{issue_key}/assignee',
      description: 'Assigns an issue to a user by their account ID.',
      wrapBody: b => ({ accountId: b.account_id }),
      params: { issue_key: { description: 'Issue key', required: true }, account_id: { description: 'Atlassian account ID of the assignee', required: true } } },
    { slug: 'list_projects', name: 'List projects', risk: 'read', path: '/rest/api/3/project/search',
      description: 'Lists Jira projects.', params: {} },
    { slug: 'list_boards', name: 'List boards', risk: 'read', path: '/rest/agile/1.0/board',
      description: 'Lists scrum/kanban boards.', params: {} },
    { slug: 'list_sprints', name: 'List sprints', risk: 'read', path: '/rest/agile/1.0/board/{board_id}/sprint',
      description: 'Sprints on a board. state: active | future | closed (optional).',
      params: { board_id: { type: 'integer', description: 'Board ID from list_boards', required: true }, state: { description: 'active | future | closed (optional)' } } },
  ],
})

export const confluenceManifest = defineRestConnector({
  slug: 'confluence',
  name: 'Confluence',
  category: 'DevOps',
  description: 'Spaces, pages, and CQL search via the Confluence Cloud REST API.',
  baseUrl: c => c.site,
  headers: c => ({ Authorization: basicAuth(c.email, c.api_token) }),
  auth: {
    ...apiKeyAuth({ service: 'Confluence', where: 'id.atlassian.com → Security → API tokens' }),
    fields: [
      { key: 'site', label: 'Confluence site', placeholder: 'yourcompany.atlassian.net', inputType: 'text' },
      { key: 'email', label: 'Account email', placeholder: 'you@company.com', inputType: 'text' },
      { key: 'api_token', label: 'API token', placeholder: 'Your Atlassian API token' },
    ],
  },
  testPath: '/wiki/rest/api/space?limit=1',
  testLabel: 'Confluence site connected',
  network: { customerHost: true },
  actions: [
    { slug: 'list_spaces', name: 'List spaces', risk: 'read', path: '/wiki/rest/api/space', staticQuery: { limit: '30' },
      description: 'Lists Confluence spaces.', params: {} },
    { slug: 'search_content', name: 'Search content (CQL)', risk: 'read', path: '/wiki/rest/api/content/search', staticQuery: { limit: '25' },
      description: 'Searches pages with CQL, e.g. cql=text ~ "runbook" AND space = OPS.',
      params: { cql: { description: 'CQL query', required: true } } },
    { slug: 'list_pages', name: 'List pages in space', risk: 'read', path: '/wiki/rest/api/content', staticQuery: { type: 'page', limit: '30' },
      description: 'Lists pages in a space by space key.',
      params: { spaceKey: { description: 'Space key, e.g. OPS', required: true } } },
    { slug: 'get_page', name: 'Get page', risk: 'read', path: '/wiki/rest/api/content/{page_id}', staticQuery: { expand: 'body.storage,version' },
      description: 'Reads one page including its body content.',
      params: { page_id: { description: 'Page ID', required: true } } },
    { slug: 'create_page', name: 'Create page', risk: 'write', method: 'POST', path: '/wiki/rest/api/content',
      description: 'Creates a page in a space. body is HTML-ish storage format (plain text is fine).',
      wrapBody: b => ({ type: 'page', title: b.title, space: { key: b.space_key }, body: { storage: { value: String(b.body ?? ''), representation: 'storage' } } }),
      params: { space_key: { description: 'Space key', required: true }, title: { description: 'Page title', required: true }, body: { description: 'Page content (plain text or storage HTML)' } } },
  ],
})

export const circleciManifest = defineRestConnector({
  slug: 'circleci',
  name: 'CircleCI',
  category: 'DevOps',
  description: 'Pipelines, workflows, and jobs via the CircleCI v2 API.',
  baseUrl: 'https://circleci.com/api/v2',
  headers: c => ({ 'Circle-Token': c.api_key }),
  auth: apiKeyAuth({ service: 'CircleCI', keyLabel: 'Personal API token', where: 'User Settings → Personal API Tokens' }),
  testPath: '/me',
  testLabel: 'CircleCI account connected',
  actions: [
    { slug: 'list_pipelines', name: 'List pipelines', risk: 'read', path: '/project/{project_slug}/pipeline',
      description: 'Recent pipelines for a project. project_slug looks like gh/org/repo.',
      params: { project_slug: { description: 'Project slug, e.g. gh/acme/api', required: true } } },
    { slug: 'trigger_pipeline', name: 'Trigger pipeline', risk: 'write', method: 'POST', path: '/project/{project_slug}/pipeline',
      description: 'Triggers a new pipeline on a branch.',
      params: { project_slug: { description: 'Project slug, e.g. gh/acme/api', required: true }, branch: { description: 'Branch to build (default main)' } } },
    { slug: 'list_workflows', name: 'List pipeline workflows', risk: 'read', path: '/pipeline/{pipeline_id}/workflow',
      description: 'Workflows (and their status) for a pipeline.',
      params: { pipeline_id: { description: 'Pipeline ID', required: true } } },
    { slug: 'list_jobs', name: 'List workflow jobs', risk: 'read', path: '/workflow/{workflow_id}/job',
      description: 'Jobs in a workflow with status.',
      params: { workflow_id: { description: 'Workflow ID', required: true } } },
    { slug: 'rerun_workflow', name: 'Rerun workflow', risk: 'write', method: 'POST', path: '/workflow/{workflow_id}/rerun',
      description: 'Reruns a workflow (from failed by default).',
      params: { workflow_id: { description: 'Workflow ID', required: true } } },
    { slug: 'cancel_workflow', name: 'Cancel workflow', risk: 'write', method: 'POST', path: '/workflow/{workflow_id}/cancel',
      description: 'Cancels a running workflow.',
      params: { workflow_id: { description: 'Workflow ID', required: true } } },
  ],
})

export const argocdManifest = defineRestConnector({
  slug: 'argocd',
  name: 'Argo CD',
  category: 'DevOps',
  description: 'GitOps applications — status, sync, and projects via the Argo CD API.',
  baseUrl: c => c.server,
  headers: c => ({ Authorization: `Bearer ${c.token}` }),
  auth: {
    ...apiKeyAuth({ service: 'Argo CD', where: 'Settings → Accounts → Generate auth token' }),
    fields: [
      { key: 'server', label: 'Server URL', placeholder: 'https://argocd.yourcompany.com', inputType: 'text' },
      { key: 'token', label: 'Auth token', placeholder: 'Your Argo CD auth token' },
    ],
  },
  testPath: '/api/v1/projects?count=1',
  testLabel: 'Argo CD server connected',
  network: { customerHost: true },
  actions: [
    { slug: 'list_applications', name: 'List applications', risk: 'read', path: '/api/v1/applications',
      description: 'All Argo CD applications with sync + health status.', params: {} },
    { slug: 'get_application', name: 'Get application', risk: 'read', path: '/api/v1/applications/{name}',
      description: 'One application with full status, resources, and conditions.',
      params: { name: { description: 'Application name', required: true } } },
    { slug: 'sync_application', name: 'Sync application', risk: 'write', method: 'POST', path: '/api/v1/applications/{name}/sync',
      description: 'Triggers a sync (deploy) of an application to its target state.',
      params: { name: { description: 'Application name', required: true } } },
    { slug: 'rollback_application', name: 'Rollback application', risk: 'destructive', method: 'POST', path: '/api/v1/applications/{name}/rollback',
      description: 'Rolls an application back to a previous deployed revision id.',
      wrapBody: b => ({ id: Number(b.history_id) }),
      params: { name: { description: 'Application name', required: true }, history_id: { type: 'integer', description: 'History deployment ID to roll back to', required: true } } },
    { slug: 'list_projects', name: 'List projects', risk: 'read', path: '/api/v1/projects',
      description: 'Argo CD projects.', params: {} },
  ],
})

export const terraformCloudManifest = defineRestConnector({
  slug: 'terraform-cloud',
  name: 'Terraform Cloud',
  category: 'DevOps',
  description: 'Workspaces and runs — plan, apply, and discard via the Terraform Cloud API.',
  baseUrl: 'https://app.terraform.io',
  headers: c => ({ Authorization: `Bearer ${c.api_key}`, 'Content-Type': 'application/vnd.api+json' }),
  auth: apiKeyAuth({ service: 'Terraform Cloud', keyLabel: 'API token', where: 'User Settings → Tokens' }),
  testPath: '/api/v2/account/details',
  testLabel: 'Terraform Cloud account connected',
  actions: [
    { slug: 'list_workspaces', name: 'List workspaces', risk: 'read', path: '/api/v2/organizations/{organization}/workspaces',
      description: 'Workspaces in an organization.',
      params: { organization: { description: 'Organization name', required: true } } },
    { slug: 'list_runs', name: 'List runs', risk: 'read', path: '/api/v2/workspaces/{workspace_id}/runs', staticQuery: { 'page[size]': '20' },
      description: 'Recent runs for a workspace with status (planned, applied, errored…).',
      params: { workspace_id: { description: 'Workspace ID (ws-…)', required: true } } },
    { slug: 'create_run', name: 'Start run (plan)', risk: 'write', method: 'POST', path: '/api/v2/runs',
      description: 'Queues a new plan run on a workspace.',
      wrapBody: b => ({ data: { type: 'runs', attributes: { message: b.message ?? 'Run started via OrbitAPI' }, relationships: { workspace: { data: { type: 'workspaces', id: b.workspace_id } } } } }),
      params: { workspace_id: { description: 'Workspace ID (ws-…)', required: true }, message: { description: 'Run message (optional)' } } },
    { slug: 'apply_run', name: 'Apply run', risk: 'destructive', method: 'POST', path: '/api/v2/runs/{run_id}/actions/apply',
      description: 'Applies a planned run — changes real infrastructure. Confirm before using.',
      wrapBody: b => ({ comment: b.comment ?? 'Applied via OrbitAPI' }),
      params: { run_id: { description: 'Run ID (run-…)', required: true }, comment: { description: 'Apply comment (optional)' } } },
    { slug: 'discard_run', name: 'Discard run', risk: 'write', method: 'POST', path: '/api/v2/runs/{run_id}/actions/discard',
      description: 'Discards a planned run without applying it.',
      params: { run_id: { description: 'Run ID (run-…)', required: true } } },
  ],
})

export const devopsConnectors = [
  githubManifest, gitlabManifest, jiraManifest, confluenceManifest,
  circleciManifest, argocdManifest, terraformCloudManifest,
]
