import { defineRestConnector, apiKeyAuth, basicAuth } from '../factory'

// Finance connectors — Stripe, Xero, Chargebee, FreshBooks, Sage Intacct, Zuora.

export const stripeManifest = defineRestConnector({
  slug: 'stripe',
  name: 'Stripe',
  category: 'Finance',
  description: 'Payments, customers, subscriptions, invoices, and refunds via the Stripe API.',
  baseUrl: 'https://api.stripe.com/v1',
  formEncoded: true,
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'Stripe', keyLabel: 'Secret key', keyPlaceholder: 'sk_live_… or sk_test_…', where: 'Dashboard → Developers → API keys', keyHint: 'Use a restricted or test key to be safe. Found in Dashboard → Developers → API keys.' }),
  testPath: '/balance',
  testLabel: 'Stripe account connected',
  actions: [
    { slug: 'get_balance', name: 'Get balance', risk: 'read', path: '/balance',
      description: 'Current available and pending balance by currency.', params: {} },
    { slug: 'list_charges', name: 'List charges', risk: 'read', path: '/charges', staticQuery: { limit: '25' },
      description: 'Recent payments (charges) with amount, status, and customer.', params: {} },
    { slug: 'list_payment_intents', name: 'List payment intents', risk: 'read', path: '/payment_intents', staticQuery: { limit: '25' },
      description: 'Recent payment intents with status (succeeded, requires_action, canceled…).', params: {} },
    { slug: 'list_customers', name: 'List customers', risk: 'read', path: '/customers', staticQuery: { limit: '25' },
      description: 'Customers, newest first. email: filter by exact email (optional).',
      params: { email: { description: 'Filter by exact email (optional)' } } },
    { slug: 'get_customer', name: 'Get customer', risk: 'read', path: '/customers/{customer_id}',
      description: 'One customer with their default payment details.',
      params: { customer_id: { description: 'Customer ID (cus_…)', required: true } } },
    { slug: 'list_subscriptions', name: 'List subscriptions', risk: 'read', path: '/subscriptions', staticQuery: { limit: '25' },
      description: 'Active subscriptions. status: all | active | canceled | past_due (optional).',
      params: { status: { description: 'Filter by status (optional)', enum: ['all', 'active', 'canceled', 'past_due', 'trialing'] } } },
    { slug: 'list_invoices', name: 'List invoices', risk: 'read', path: '/invoices', staticQuery: { limit: '25' },
      description: 'Recent invoices with amount due/paid and status.',
      params: { customer: { description: 'Filter by customer ID (optional)' }, status: { description: 'draft | open | paid | void | uncollectible (optional)', enum: ['draft', 'open', 'paid', 'void', 'uncollectible'] } } },
    { slug: 'list_payouts', name: 'List payouts', risk: 'read', path: '/payouts', staticQuery: { limit: '20' },
      description: 'Payouts to your bank with arrival dates.', params: {} },
    { slug: 'list_refunds', name: 'List refunds', risk: 'read', path: '/refunds', staticQuery: { limit: '20' },
      description: 'Recent refunds.', params: {} },
    { slug: 'create_refund', name: 'Refund a charge', risk: 'destructive', method: 'POST', path: '/refunds',
      description: 'Refunds a charge (fully, or amount in cents for partial). Moves real money — confirm before using.',
      params: { charge: { description: 'Charge ID (ch_…) to refund', required: true }, amount: { type: 'integer', description: 'Partial amount in cents (optional — omit for full refund)' } } },
    { slug: 'cancel_subscription', name: 'Cancel subscription', risk: 'destructive', method: 'DELETE', path: '/subscriptions/{subscription_id}',
      description: 'Cancels a subscription immediately. Confirm before using.',
      params: { subscription_id: { description: 'Subscription ID (sub_…)', required: true } } },
  ],
})

export const xeroManifest = defineRestConnector({
  slug: 'xero',
  name: 'Xero',
  category: 'Finance',
  description: 'Invoices, contacts, bills, and P&L via the Xero accounting API.',
  baseUrl: 'https://api.xero.com/api.xro/2.0',
  headers: c => ({ Authorization: `Bearer ${c.access_token}`, 'Xero-tenant-id': c.tenant_id }),
  auth: {
    ...apiKeyAuth({ service: 'Xero', where: 'developer.xero.com → My Apps (OAuth token + tenant id)' }),
    fields: [
      { key: 'access_token', label: 'OAuth access token', placeholder: 'Your Xero OAuth token', hint: 'Advanced — most people should use Simulate mode.' },
      { key: 'tenant_id', label: 'Tenant ID', placeholder: 'Organisation tenant UUID', inputType: 'text' },
    ],
  },
  testPath: '/Organisation',
  testLabel: 'Xero organisation connected',
  actions: [
    { slug: 'list_invoices', name: 'List invoices', risk: 'read', path: '/Invoices', staticQuery: { page: '1' },
      description: 'Sales invoices with status and amounts. where: Xero filter, e.g. Status=="AUTHORISED" (optional).',
      params: { where: { description: 'Xero where filter (optional)' } } },
    { slug: 'get_invoice', name: 'Get invoice', risk: 'read', path: '/Invoices/{invoice_id}',
      description: 'One invoice with line items.',
      params: { invoice_id: { description: 'Invoice ID or number', required: true } } },
    { slug: 'list_contacts', name: 'List contacts', risk: 'read', path: '/Contacts', staticQuery: { page: '1' },
      description: 'Customers and suppliers.', params: {} },
    { slug: 'list_bills', name: 'List bills (payables)', risk: 'read', path: '/Invoices', staticQuery: { where: 'Type=="ACCPAY"', page: '1' },
      description: 'Bills you owe (accounts payable).', params: {} },
    { slug: 'get_profit_and_loss', name: 'Profit & Loss report', risk: 'read', path: '/Reports/ProfitAndLoss',
      description: 'P&L for a date range (YYYY-MM-DD).',
      params: { fromDate: { description: 'Start date (optional)' }, toDate: { description: 'End date (optional)' } } },
    { slug: 'get_balance_sheet', name: 'Balance Sheet report', risk: 'read', path: '/Reports/BalanceSheet',
      description: 'Balance sheet as of a date.',
      params: { date: { description: 'As-of date YYYY-MM-DD (optional)' } } },
    { slug: 'create_invoice', name: 'Create draft invoice', risk: 'write', method: 'POST', path: '/Invoices',
      description: 'Creates a DRAFT sales invoice for a contact with one line item.',
      wrapBody: b => ({ Invoices: [{ Type: 'ACCREC', Status: 'DRAFT', Contact: { Name: b.contact_name }, LineItems: [{ Description: b.description, Quantity: 1, UnitAmount: Number(b.amount ?? 0) }] }] }),
      params: { contact_name: { description: 'Customer name', required: true }, description: { description: 'Line item description', required: true }, amount: { type: 'number', description: 'Amount (ex tax)', required: true } } },
  ],
})

export const chargebeeManifest = defineRestConnector({
  slug: 'chargebee',
  name: 'Chargebee',
  category: 'Finance',
  description: 'Subscriptions, customers, and invoices via the Chargebee API.',
  baseUrl: c => `https://${c.site}.chargebee.com/api/v2`,
  headers: c => ({ Authorization: basicAuth(c.api_key, '') }),
  auth: {
    ...apiKeyAuth({ service: 'Chargebee', where: 'Settings → Configure Chargebee → API Keys' }),
    fields: [
      { key: 'site', label: 'Site name', placeholder: 'yourcompany (from yourcompany.chargebee.com)', inputType: 'text' },
      { key: 'api_key', label: 'API key', placeholder: 'live_… or test_…' },
    ],
  },
  testPath: '/customers?limit=1',
  testLabel: 'Chargebee site connected',
  actions: [
    { slug: 'list_subscriptions', name: 'List subscriptions', risk: 'read', path: '/subscriptions', staticQuery: { limit: '25' },
      description: 'Subscriptions with plan, status, and MRR contribution.', params: {} },
    { slug: 'list_customers', name: 'List customers', risk: 'read', path: '/customers', staticQuery: { limit: '25' },
      description: 'Customers, newest first.', params: {} },
    { slug: 'list_invoices', name: 'List invoices', risk: 'read', path: '/invoices', staticQuery: { limit: '25' },
      description: 'Invoices with amounts and status.', params: {} },
    { slug: 'get_subscription', name: 'Get subscription', risk: 'read', path: '/subscriptions/{subscription_id}',
      description: 'One subscription with items and billing dates.',
      params: { subscription_id: { description: 'Subscription ID', required: true } } },
    { slug: 'cancel_subscription', name: 'Cancel subscription', risk: 'destructive', method: 'POST', path: '/subscriptions/{subscription_id}/cancel_for_items',
      description: 'Cancels a subscription (end of term by default). Confirm before using.',
      wrapBody: () => ({ end_of_term: true }),
      params: { subscription_id: { description: 'Subscription ID', required: true } } },
  ],
})

export const freshbooksManifest = defineRestConnector({
  slug: 'freshbooks',
  name: 'FreshBooks',
  category: 'Finance',
  description: 'Invoices, clients, and expenses via the FreshBooks API.',
  baseUrl: 'https://api.freshbooks.com',
  headers: c => ({ Authorization: `Bearer ${c.access_token}` }),
  auth: {
    ...apiKeyAuth({ service: 'FreshBooks', where: 'my.freshbooks.com → Settings → Developer Portal (OAuth token)' }),
    fields: [
      { key: 'access_token', label: 'OAuth access token', placeholder: 'Your FreshBooks bearer token', hint: 'Advanced — most people should use Simulate mode.' },
      { key: 'account_id', label: 'Account ID', placeholder: 'e.g. ABC123', inputType: 'text' },
    ],
  },
  testPath: '/auth/api/v1/users/me',
  testLabel: 'FreshBooks account connected',
  actions: [
    { slug: 'list_invoices', name: 'List invoices', risk: 'read', path: '/accounting/account/{account_id}/invoices/invoices',
      description: 'Invoices with amounts and status.',
      params: { account_id: { description: 'Account ID', required: true } } },
    { slug: 'list_clients', name: 'List clients', risk: 'read', path: '/accounting/account/{account_id}/users/clients',
      description: 'Clients with contact info and outstanding balance.',
      params: { account_id: { description: 'Account ID', required: true } } },
    { slug: 'list_expenses', name: 'List expenses', risk: 'read', path: '/accounting/account/{account_id}/expenses/expenses',
      description: 'Expenses with categories and amounts.',
      params: { account_id: { description: 'Account ID', required: true } } },
    { slug: 'list_payments', name: 'List payments', risk: 'read', path: '/accounting/account/{account_id}/payments/payments',
      description: 'Payments received against invoices.',
      params: { account_id: { description: 'Account ID', required: true } } },
  ],
})

export const sageIntacctManifest = defineRestConnector({
  slug: 'sage-intacct',
  name: 'Sage Intacct',
  category: 'Finance',
  description: 'GL accounts, invoices, vendors, and reports via the Sage Intacct REST API.',
  baseUrl: 'https://api.intacct.com/ia/api/v1',
  headers: c => ({ Authorization: `Bearer ${c.access_token}` }),
  auth: {
    ...apiKeyAuth({ service: 'Sage Intacct', where: 'Company → Web Services (OAuth token)' }),
    fields: [
      { key: 'access_token', label: 'OAuth access token', placeholder: 'Your Intacct bearer token', hint: 'Advanced — most people should use Simulate mode.' },
    ],
  },
  testPath: '/services/core/model?name=general-ledger/account',
  testLabel: 'Sage Intacct connected',
  actions: [
    { slug: 'list_gl_accounts', name: 'List GL accounts', risk: 'read', path: '/objects/general-ledger/account', staticQuery: { size: '50' },
      description: 'Chart of accounts.', params: {} },
    { slug: 'list_ar_invoices', name: 'List AR invoices', risk: 'read', path: '/objects/accounts-receivable/invoice', staticQuery: { size: '25' },
      description: 'Accounts-receivable invoices with balances.', params: {} },
    { slug: 'list_ap_bills', name: 'List AP bills', risk: 'read', path: '/objects/accounts-payable/bill', staticQuery: { size: '25' },
      description: 'Accounts-payable bills with due dates.', params: {} },
    { slug: 'list_vendors', name: 'List vendors', risk: 'read', path: '/objects/accounts-payable/vendor', staticQuery: { size: '50' },
      description: 'Vendors with contact info.', params: {} },
    { slug: 'list_customers', name: 'List customers', risk: 'read', path: '/objects/accounts-receivable/customer', staticQuery: { size: '50' },
      description: 'Customers with balances.', params: {} },
  ],
})

export const zuoraManifest = defineRestConnector({
  slug: 'zuora',
  name: 'Zuora',
  category: 'Finance',
  description: 'Subscriptions, accounts, and invoices via the Zuora REST API.',
  baseUrl: c => c.environment === 'sandbox' ? 'https://rest.apisandbox.zuora.com' : 'https://rest.zuora.com',
  headers: c => ({ Authorization: `Bearer ${c.access_token}` }),
  auth: {
    ...apiKeyAuth({ service: 'Zuora', where: 'Settings → Administration → OAuth (client credentials → token)' }),
    fields: [
      { key: 'access_token', label: 'OAuth access token', placeholder: 'Your Zuora bearer token', hint: 'Advanced — most people should use Simulate mode.' },
      { key: 'environment', label: 'Environment', placeholder: 'production or sandbox', inputType: 'text', hint: 'Type "sandbox" for the API sandbox, otherwise leave as production.' },
    ],
  },
  testPath: '/v1/catalog/products?pageSize=1',
  testLabel: 'Zuora tenant connected',
  actions: [
    { slug: 'list_accounts', name: 'List billing accounts', risk: 'read', method: 'POST', path: '/v1/action/query',
      description: 'Billing accounts with balances (ZOQL query).',
      wrapBody: () => ({ queryString: 'select Id, Name, AccountNumber, Balance, Status from Account' }),
      params: {} },
    { slug: 'get_account', name: 'Get account', risk: 'read', path: '/v1/accounts/{account_key}',
      description: 'One billing account with contacts and balance.',
      params: { account_key: { description: 'Account number or ID', required: true } } },
    { slug: 'list_subscriptions', name: 'List subscriptions for account', risk: 'read', path: '/v1/subscriptions/accounts/{account_key}',
      description: 'Subscriptions on a billing account.',
      params: { account_key: { description: 'Account number or ID', required: true } } },
    { slug: 'list_invoices', name: 'List invoices for account', risk: 'read', path: '/v1/transactions/invoices/accounts/{account_key}',
      description: 'Invoices for a billing account.',
      params: { account_key: { description: 'Account number or ID', required: true } } },
    { slug: 'list_products', name: 'List product catalog', risk: 'read', path: '/v1/catalog/products', staticQuery: { pageSize: '25' },
      description: 'Products and rate plans in the catalog.', params: {} },
  ],
})

export const financeConnectors = [
  stripeManifest, xeroManifest, chargebeeManifest, freshbooksManifest,
  sageIntacctManifest, zuoraManifest,
]
