import { defineRestConnector, apiKeyAuth, basicAuth } from '../factory'

// Incident Management + Short-Term Rental + Smart Home connectors.

export const opsgenieManifest = defineRestConnector({
  slug: 'opsgenie',
  name: 'OpsGenie',
  category: 'Incident Management',
  description: 'Alerts, schedules, and on-call via the OpsGenie API.',
  baseUrl: 'https://api.opsgenie.com',
  headers: c => ({ Authorization: `GenieKey ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'OpsGenie', keyLabel: 'API key', where: 'Settings → API key management' }),
  testPath: '/v2/account',
  testLabel: 'OpsGenie account connected',
  actions: [
    { slug: 'list_alerts', name: 'List alerts', risk: 'read', path: '/v2/alerts', staticQuery: { limit: '25', sort: 'createdAt', order: 'desc' },
      description: 'Recent alerts. query: e.g. status:open (optional).',
      params: { query: { description: 'Search query, e.g. status:open (optional)' } } },
    { slug: 'create_alert', name: 'Create alert', risk: 'write', method: 'POST', path: '/v2/alerts',
      description: 'Raises an alert. priority P1 (critical) – P5 (info).',
      wrapBody: b => ({ message: b.message, priority: b.priority ?? 'P3', ...(b.description ? { description: b.description } : {}) }),
      params: { message: { description: 'Alert message', required: true }, priority: { description: 'P1–P5 (default P3)', enum: ['P1', 'P2', 'P3', 'P4', 'P5'] }, description: { description: 'Details (optional)' } } },
    { slug: 'acknowledge_alert', name: 'Acknowledge alert', risk: 'write', method: 'POST', path: '/v2/alerts/{alert_id}/acknowledge', staticQuery: { identifierType: 'id' },
      description: 'Acknowledges an alert.',
      params: { alert_id: { description: 'Alert ID', required: true } } },
    { slug: 'close_alert', name: 'Close alert', risk: 'write', method: 'POST', path: '/v2/alerts/{alert_id}/close', staticQuery: { identifierType: 'id' },
      description: 'Closes an alert.',
      params: { alert_id: { description: 'Alert ID', required: true } } },
    { slug: 'list_schedules', name: 'List schedules', risk: 'read', path: '/v2/schedules',
      description: 'On-call schedules.', params: {} },
    { slug: 'get_on_calls', name: 'Who is on call', risk: 'read', path: '/v2/schedules/{schedule_id}/on-calls',
      description: 'Current on-call participants for a schedule.',
      params: { schedule_id: { description: 'Schedule ID', required: true } } },
    { slug: 'list_teams', name: 'List teams', risk: 'read', path: '/v2/teams',
      description: 'OpsGenie teams.', params: {} },
  ],
})

export const freshserviceManifest = defineRestConnector({
  slug: 'freshservice',
  name: 'Freshservice',
  category: 'Incident Management',
  description: 'ITSM tickets, changes, and assets via the Freshservice API.',
  baseUrl: c => `https://${c.domain}.freshservice.com/api/v2`,
  headers: c => ({ Authorization: basicAuth(c.api_key, 'X') }),
  auth: {
    ...apiKeyAuth({ service: 'Freshservice', where: 'Profile Settings → API Key' }),
    fields: [
      { key: 'domain', label: 'Freshservice domain', placeholder: 'yourcompany (from yourcompany.freshservice.com)', inputType: 'text' },
      { key: 'api_key', label: 'API key', placeholder: 'Your Freshservice API key' },
    ],
  },
  testPath: '/tickets?per_page=1',
  testLabel: 'Freshservice connected',
  actions: [
    { slug: 'list_tickets', name: 'List tickets', risk: 'read', path: '/tickets', staticQuery: { per_page: '30' },
      description: 'Service desk tickets with status and priority.', params: {} },
    { slug: 'get_ticket', name: 'Get ticket', risk: 'read', path: '/tickets/{ticket_id}',
      description: 'One ticket with details.',
      params: { ticket_id: { type: 'integer', description: 'Ticket ID', required: true } } },
    { slug: 'create_ticket', name: 'Create ticket', risk: 'write', method: 'POST', path: '/tickets',
      description: 'Creates a ticket. priority 1 low – 4 urgent.',
      wrapBody: b => ({ subject: b.subject, description: b.description, email: b.email, priority: Number(b.priority ?? 1), status: 2 }),
      params: { subject: { description: 'Subject', required: true }, description: { description: 'Details', required: true }, email: { description: 'Requester email', required: true }, priority: { type: 'integer', description: '1–4 (default 1)' } } },
    { slug: 'add_note', name: 'Add note to ticket', risk: 'write', method: 'POST', path: '/tickets/{ticket_id}/notes',
      description: 'Adds a private note to a ticket.',
      wrapBody: b => ({ body: b.body, private: true }),
      params: { ticket_id: { type: 'integer', description: 'Ticket ID', required: true }, body: { description: 'Note text', required: true } } },
    { slug: 'list_changes', name: 'List changes', risk: 'read', path: '/changes', staticQuery: { per_page: '30' },
      description: 'Change requests with status.', params: {} },
    { slug: 'list_assets', name: 'List assets', risk: 'read', path: '/assets', staticQuery: { per_page: '30' },
      description: 'IT assets in the CMDB.', params: {} },
  ],
})

export const jiraServiceManifest = defineRestConnector({
  slug: 'jira-service',
  name: 'Jira Service Management',
  category: 'Incident Management',
  description: 'Service desks, requests, and queues via the JSM API.',
  baseUrl: c => c.site,
  headers: c => ({ Authorization: basicAuth(c.email, c.api_token) }),
  auth: {
    ...apiKeyAuth({ service: 'Jira Service Management', where: 'id.atlassian.com → Security → API tokens' }),
    fields: [
      { key: 'site', label: 'Site', placeholder: 'yourcompany.atlassian.net', inputType: 'text' },
      { key: 'email', label: 'Account email', placeholder: 'you@company.com', inputType: 'text' },
      { key: 'api_token', label: 'API token', placeholder: 'Your Atlassian API token' },
    ],
  },
  testPath: '/rest/servicedeskapi/servicedesk',
  testLabel: 'JSM site connected',
  actions: [
    { slug: 'list_service_desks', name: 'List service desks', risk: 'read', path: '/rest/servicedeskapi/servicedesk',
      description: 'Service desks with project keys.', params: {} },
    { slug: 'list_requests', name: 'List my requests', risk: 'read', path: '/rest/servicedeskapi/request',
      description: 'Customer requests visible to this account.', params: {} },
    { slug: 'list_request_types', name: 'List request types', risk: 'read', path: '/rest/servicedeskapi/servicedesk/{service_desk_id}/requesttype',
      description: 'Request types for a service desk (needed to create requests).',
      params: { service_desk_id: { description: 'Service desk ID', required: true } } },
    { slug: 'create_request', name: 'Create request', risk: 'write', method: 'POST', path: '/rest/servicedeskapi/request',
      description: 'Raises a service request.',
      wrapBody: b => ({ serviceDeskId: b.service_desk_id, requestTypeId: b.request_type_id, requestFieldValues: { summary: b.summary, ...(b.description ? { description: b.description } : {}) } }),
      params: { service_desk_id: { description: 'Service desk ID', required: true }, request_type_id: { description: 'Request type ID', required: true }, summary: { description: 'Request summary', required: true }, description: { description: 'Details (optional)' } } },
    { slug: 'add_comment', name: 'Comment on request', risk: 'write', method: 'POST', path: '/rest/servicedeskapi/request/{issue_key}/comment',
      description: 'Adds a public comment to a request.',
      wrapBody: b => ({ body: b.body, public: true }),
      params: { issue_key: { description: 'Request key, e.g. HELP-42', required: true }, body: { description: 'Comment text', required: true } } },
    { slug: 'list_queues', name: 'List queues', risk: 'read', path: '/rest/servicedeskapi/servicedesk/{service_desk_id}/queue',
      description: 'Agent queues with issue counts.',
      params: { service_desk_id: { description: 'Service desk ID', required: true } } },
  ],
})

export const xmattersManifest = defineRestConnector({
  slug: 'xmatters',
  name: 'xMatters',
  category: 'Incident Management',
  description: 'Events, people, groups, and on-call via the xMatters API.',
  baseUrl: c => `https://${c.instance}.xmatters.com/api/xm/1`,
  headers: c => ({ Authorization: basicAuth(c.username, c.password) }),
  auth: {
    ...apiKeyAuth({ service: 'xMatters', where: 'your instance (REST user credentials)' }),
    fields: [
      { key: 'instance', label: 'Instance', placeholder: 'yourcompany (from yourcompany.xmatters.com)', inputType: 'text' },
      { key: 'username', label: 'Username', placeholder: 'REST API user', inputType: 'text' },
      { key: 'password', label: 'Password', placeholder: 'REST API password' },
    ],
  },
  testPath: '/people?limit=1',
  testLabel: 'xMatters instance connected',
  actions: [
    { slug: 'list_events', name: 'List events', risk: 'read', path: '/events', staticQuery: { limit: '25', sortBy: 'START_TIME', sortOrder: 'DESCENDING' },
      description: 'Recent notification events with status.', params: {} },
    { slug: 'get_event', name: 'Get event', risk: 'read', path: '/events/{event_id}',
      description: 'One event with targeted recipients.',
      params: { event_id: { description: 'Event ID', required: true } } },
    { slug: 'list_people', name: 'List people', risk: 'read', path: '/people', staticQuery: { limit: '30' },
      description: 'Users. search: name filter (optional).',
      params: { search: { description: 'Name search (optional)' } } },
    { slug: 'list_groups', name: 'List groups', risk: 'read', path: '/groups', staticQuery: { limit: '30' },
      description: 'Notification groups.', params: {} },
    { slug: 'get_on_call', name: 'Who is on call', risk: 'read', path: '/on-call', staticQuery: { membersPerShift: '5' },
      description: 'Current on-call members for comma-separated group names.',
      params: { groups: { description: 'Group name(s), comma-separated', required: true } } },
  ],
})

// ── Short-Term Rental ────────────────────────────────────────────────────────

export const guestyManifest = defineRestConnector({
  slug: 'guesty',
  name: 'Guesty',
  category: 'Short-Term Rental',
  description: 'Listings, reservations, and guests via the Guesty Open API.',
  baseUrl: 'https://open-api.guesty.com/v1',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'Guesty', keyLabel: 'API token', where: 'Integrations → API (Open API token)' }),
  testPath: '/listings?limit=1',
  testLabel: 'Guesty account connected',
  actions: [
    { slug: 'list_listings', name: 'List listings', risk: 'read', path: '/listings', staticQuery: { limit: '25' },
      description: 'Properties with address and status.', params: {} },
    { slug: 'get_listing', name: 'Get listing', risk: 'read', path: '/listings/{listing_id}',
      description: 'One listing with full details.',
      params: { listing_id: { description: 'Listing ID', required: true } } },
    { slug: 'list_reservations', name: 'List reservations', risk: 'read', path: '/reservations', staticQuery: { limit: '25', sort: '-checkIn' },
      description: 'Reservations with check-in/out and status.', params: {} },
    { slug: 'get_reservation', name: 'Get reservation', risk: 'read', path: '/reservations/{reservation_id}',
      description: 'One reservation with guest and money details.',
      params: { reservation_id: { description: 'Reservation ID', required: true } } },
    { slug: 'list_guests', name: 'List guests', risk: 'read', path: '/guests', staticQuery: { limit: '25' },
      description: 'Guest profiles.', params: {} },
  ],
})

export const hostawayManifest = defineRestConnector({
  slug: 'hostaway',
  name: 'Hostaway',
  category: 'Short-Term Rental',
  description: 'Listings, reservations, and guest messaging via the Hostaway API.',
  baseUrl: 'https://api.hostaway.com/v1',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'Hostaway', keyLabel: 'Access token', where: 'Settings → Hostaway API (create access token)' }),
  testPath: '/listings?limit=1',
  testLabel: 'Hostaway account connected',
  actions: [
    { slug: 'list_listings', name: 'List listings', risk: 'read', path: '/listings', staticQuery: { limit: '25' },
      description: 'Properties with address and channel status.', params: {} },
    { slug: 'list_reservations', name: 'List reservations', risk: 'read', path: '/reservations', staticQuery: { limit: '25', sortOrder: 'arrivalDate' },
      description: 'Reservations with arrival/departure and status.', params: {} },
    { slug: 'get_reservation', name: 'Get reservation', risk: 'read', path: '/reservations/{reservation_id}',
      description: 'One reservation with guest details.',
      params: { reservation_id: { type: 'integer', description: 'Reservation ID', required: true } } },
    { slug: 'get_calendar', name: 'Get listing calendar', risk: 'read', path: '/listings/{listing_id}/calendar',
      description: 'Availability and prices. startDate/endDate: YYYY-MM-DD.',
      params: { listing_id: { type: 'integer', description: 'Listing ID', required: true }, startDate: { description: 'YYYY-MM-DD' }, endDate: { description: 'YYYY-MM-DD' } } },
    { slug: 'list_conversations', name: 'List conversations', risk: 'read', path: '/conversations', staticQuery: { limit: '25' },
      description: 'Guest message threads.', params: {} },
    { slug: 'send_message', name: 'Send guest message', risk: 'write', method: 'POST', path: '/conversations/{conversation_id}/messages',
      description: 'Sends a message in a guest conversation. Confirm before sending.',
      wrapBody: b => ({ body: b.body }),
      params: { conversation_id: { type: 'integer', description: 'Conversation ID', required: true }, body: { description: 'Message text', required: true } } },
  ],
})

export const ownerrezManifest = defineRestConnector({
  slug: 'ownerrez',
  name: 'OwnerRez',
  category: 'Short-Term Rental',
  description: 'Properties, bookings, and guests via the OwnerRez API.',
  baseUrl: 'https://api.ownerrez.com',
  headers: c => ({ Authorization: basicAuth(c.username, c.token) }),
  auth: {
    ...apiKeyAuth({ service: 'OwnerRez', where: 'Settings → API → Create Personal Access Token' }),
    fields: [
      { key: 'username', label: 'Account email', placeholder: 'you@company.com', inputType: 'text' },
      { key: 'token', label: 'Personal access token', placeholder: 'pt_…' },
    ],
  },
  testPath: '/v2/users/me',
  testLabel: 'OwnerRez account connected',
  actions: [
    { slug: 'list_properties', name: 'List properties', risk: 'read', path: '/v2/properties',
      description: 'Your properties.', params: {} },
    { slug: 'list_bookings', name: 'List bookings', risk: 'read', path: '/v2/bookings',
      description: 'Bookings. since_utc: ISO date to start from (optional).',
      params: { since_utc: { description: 'ISO date, e.g. 2026-06-01 (optional)' }, property_ids: { description: 'Comma-separated property IDs (optional)' } } },
    { slug: 'get_booking', name: 'Get booking', risk: 'read', path: '/v2/bookings/{booking_id}',
      description: 'One booking with charges and guest.',
      params: { booking_id: { type: 'integer', description: 'Booking ID', required: true } } },
    { slug: 'list_guests', name: 'List guests', risk: 'read', path: '/v2/guests',
      description: 'Guests. created_since_utc: ISO date (optional).',
      params: { created_since_utc: { description: 'ISO date (optional)' } } },
  ],
})

export const hostfullyManifest = defineRestConnector({
  slug: 'hostfully',
  name: 'Hostfully',
  category: 'Short-Term Rental',
  description: 'Properties and leads via the Hostfully Property Management API.',
  baseUrl: 'https://api.hostfully.com/v3',
  headers: c => ({ 'X-HOSTFULLY-APIKEY': c.api_key }),
  auth: {
    ...apiKeyAuth({ service: 'Hostfully', where: 'Agency Settings → API Management' }),
    fields: [
      { key: 'api_key', label: 'API key', placeholder: 'Your Hostfully API key' },
      { key: 'agency_uid', label: 'Agency UID', placeholder: 'Your agency UUID', inputType: 'text' },
    ],
  },
  testPath: '/agencies',
  testLabel: 'Hostfully agency connected',
  actions: [
    { slug: 'list_properties', name: 'List properties', risk: 'read', path: '/properties',
      description: 'Properties for your agency.',
      params: { agencyUid: { description: 'Agency UID', required: true } } },
    { slug: 'get_property', name: 'Get property', risk: 'read', path: '/properties/{property_uid}',
      description: 'One property with details.',
      params: { property_uid: { description: 'Property UID', required: true } } },
    { slug: 'list_leads', name: 'List leads/bookings', risk: 'read', path: '/leads',
      description: 'Leads and bookings for a property.',
      params: { propertyUid: { description: 'Property UID', required: true } } },
  ],
})

export const beds24Manifest = defineRestConnector({
  slug: 'beds24',
  name: 'Beds24',
  category: 'Short-Term Rental',
  description: 'Properties and bookings via the Beds24 v2 API.',
  baseUrl: 'https://api.beds24.com/v2',
  headers: c => ({ token: c.api_key }),
  auth: apiKeyAuth({ service: 'Beds24', keyLabel: 'API token', where: 'Settings → Apps & Integrations → API' }),
  testPath: '/properties?page=1',
  testLabel: 'Beds24 account connected',
  actions: [
    { slug: 'list_properties', name: 'List properties', risk: 'read', path: '/properties',
      description: 'Properties with rooms.', params: {} },
    { slug: 'list_bookings', name: 'List bookings', risk: 'read', path: '/bookings',
      description: 'Bookings. arrivalFrom/arrivalTo: YYYY-MM-DD (optional).',
      params: { arrivalFrom: { description: 'YYYY-MM-DD (optional)' }, arrivalTo: { description: 'YYYY-MM-DD (optional)' }, status: { description: 'confirmed | new | cancelled (optional)' } } },
    { slug: 'get_booking', name: 'Get booking', risk: 'read', path: '/bookings', staticQuery: {},
      description: 'One booking by ID.',
      params: { id: { type: 'integer', description: 'Booking ID', required: true } } },
  ],
})

// ── Smart Home ───────────────────────────────────────────────────────────────

export const philipsHueManifest = defineRestConnector({
  slug: 'philips-hue',
  name: 'Philips Hue',
  category: 'Smart Home',
  description: 'Lights, rooms, and scenes on your local Hue Bridge.',
  baseUrl: c => `http://${c.bridge_ip}/api/${c.app_key}`,
  headers: () => ({}),
  auth: {
    ...apiKeyAuth({ service: 'Philips Hue', where: 'your Hue Bridge (press the link button, then create an app key)', keyHint: 'Works on your local network only — the OrbitAPI server must reach the bridge. Simulate mode works anywhere.' }),
    fields: [
      { key: 'bridge_ip', label: 'Bridge IP', placeholder: '192.168.1.2', inputType: 'text' },
      { key: 'app_key', label: 'App key (username)', placeholder: 'Generated bridge username' },
    ],
  },
  testPath: '/config',
  testLabel: 'Hue Bridge connected',
  actions: [
    { slug: 'list_lights', name: 'List lights', risk: 'read', path: '/lights',
      description: 'All lights with on/off and brightness state.', params: {} },
    { slug: 'set_light_state', name: 'Set light state', risk: 'write', method: 'PUT', path: '/lights/{light_id}/state',
      description: 'Turns a light on/off and sets brightness 0–254.',
      wrapBody: b => ({ ...(b.on !== undefined ? { on: Boolean(b.on) } : {}), ...(b.brightness !== undefined ? { bri: Number(b.brightness) } : {}) }),
      params: { light_id: { description: 'Light ID from list_lights', required: true }, on: { type: 'boolean', description: 'true = on, false = off' }, brightness: { type: 'integer', description: '0–254 (optional)' } } },
    { slug: 'list_groups', name: 'List rooms/groups', risk: 'read', path: '/groups',
      description: 'Rooms and zones.', params: {} },
    { slug: 'set_group_state', name: 'Set room state', risk: 'write', method: 'PUT', path: '/groups/{group_id}/action',
      description: 'Controls all lights in a room at once.',
      wrapBody: b => ({ ...(b.on !== undefined ? { on: Boolean(b.on) } : {}), ...(b.brightness !== undefined ? { bri: Number(b.brightness) } : {}) }),
      params: { group_id: { description: 'Group ID from list_groups', required: true }, on: { type: 'boolean', description: 'true/false' }, brightness: { type: 'integer', description: '0–254 (optional)' } } },
    { slug: 'list_scenes', name: 'List scenes', risk: 'read', path: '/scenes',
      description: 'Saved scenes.', params: {} },
    { slug: 'activate_scene', name: 'Activate scene', risk: 'write', method: 'PUT', path: '/groups/0/action',
      description: 'Applies a scene.',
      wrapBody: b => ({ scene: b.scene_id }),
      params: { scene_id: { description: 'Scene ID from list_scenes', required: true } } },
  ],
})

export const smartthingsManifest = defineRestConnector({
  slug: 'smartthings',
  name: 'Samsung SmartThings',
  category: 'Smart Home',
  description: 'Devices, scenes, and commands via the SmartThings API.',
  baseUrl: 'https://api.smartthings.com/v1',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'SmartThings', keyLabel: 'Personal access token', where: 'account.smartthings.com/tokens' }),
  testPath: '/locations',
  testLabel: 'SmartThings account connected',
  actions: [
    { slug: 'list_devices', name: 'List devices', risk: 'read', path: '/devices',
      description: 'All devices with capabilities.', params: {} },
    { slug: 'get_device_status', name: 'Get device status', risk: 'read', path: '/devices/{device_id}/status',
      description: 'Live state of one device.',
      params: { device_id: { description: 'Device ID', required: true } } },
    { slug: 'execute_command', name: 'Send device command', risk: 'write', method: 'POST', path: '/devices/{device_id}/commands',
      description: 'Sends a command, e.g. capability "switch", command "on".',
      wrapBody: b => ({ commands: [{ component: 'main', capability: b.capability, command: b.command, arguments: [] }] }),
      params: { device_id: { description: 'Device ID', required: true }, capability: { description: 'e.g. switch, switchLevel, lock', required: true }, command: { description: 'e.g. on, off, lock, unlock', required: true } } },
    { slug: 'list_scenes', name: 'List scenes', risk: 'read', path: '/scenes',
      description: 'Saved scenes.', params: {} },
    { slug: 'execute_scene', name: 'Run scene', risk: 'write', method: 'POST', path: '/scenes/{scene_id}/execute',
      description: 'Runs a scene.',
      params: { scene_id: { description: 'Scene ID', required: true } } },
  ],
})

export const ecobeeManifest = defineRestConnector({
  slug: 'ecobee',
  name: 'Ecobee',
  category: 'Smart Home',
  description: 'Thermostats — read state and set temperature holds via the ecobee API.',
  baseUrl: 'https://api.ecobee.com',
  headers: c => ({ Authorization: `Bearer ${c.access_token}` }),
  auth: apiKeyAuth({ service: 'ecobee', keyLabel: 'OAuth access token', where: 'ecobee developer portal (PIN flow)', keyHint: 'Advanced — most people should use Simulate mode.' }),
  testPath: '/1/thermostat?json=%7B%22selection%22%3A%7B%22selectionType%22%3A%22registered%22%2C%22selectionMatch%22%3A%22%22%7D%7D',
  testLabel: 'ecobee account connected',
  actions: [
    { slug: 'list_thermostats', name: 'List thermostats', risk: 'read', path: '/1/thermostat',
      staticQuery: { json: '{"selection":{"selectionType":"registered","selectionMatch":"","includeRuntime":true,"includeSettings":true}}' },
      description: 'Thermostats with current temperature and mode.', params: {} },
    { slug: 'set_hold', name: 'Set temperature hold', risk: 'write', method: 'POST', path: '/1/thermostat', staticQuery: { format: 'json' },
      description: 'Holds heat/cool set points (°F × 10, e.g. 720 = 72.0°F) until the next schedule change.',
      wrapBody: b => ({ selection: { selectionType: 'registered', selectionMatch: '' }, functions: [{ type: 'setHold', params: { holdType: 'nextTransition', heatHoldTemp: Number(b.heat_temp), coolHoldTemp: Number(b.cool_temp) } }] }),
      params: { heat_temp: { type: 'integer', description: 'Heat set point ×10 (e.g. 680)', required: true }, cool_temp: { type: 'integer', description: 'Cool set point ×10 (e.g. 760)', required: true } } },
    { slug: 'resume_program', name: 'Resume schedule', risk: 'write', method: 'POST', path: '/1/thermostat', staticQuery: { format: 'json' },
      description: 'Cancels holds and resumes the normal program.',
      wrapBody: () => ({ selection: { selectionType: 'registered', selectionMatch: '' }, functions: [{ type: 'resumeProgram', params: { resumeAll: true } }] }),
      params: {} },
  ],
})

export const googleHomeManifest = defineRestConnector({
  slug: 'google-home',
  name: 'Google Home / Nest',
  category: 'Smart Home',
  description: 'Nest devices via the Smart Device Management API.',
  baseUrl: 'https://smartdevicemanagement.googleapis.com/v1',
  headers: c => ({ Authorization: `Bearer ${c.access_token}` }),
  auth: {
    ...apiKeyAuth({ service: 'Google Nest', where: 'Device Access Console + OAuth', keyHint: 'Advanced — most people should use Simulate mode.' }),
    fields: [
      { key: 'access_token', label: 'OAuth access token', placeholder: 'ya29.…' },
      { key: 'project_id', label: 'Device Access project ID', placeholder: 'UUID from console.nest.google.com', inputType: 'text' },
    ],
  },
  testPath: '/enterprises/-/devices',
  testLabel: 'Nest account connected',
  actions: [
    { slug: 'list_devices', name: 'List devices', risk: 'read', path: '/enterprises/{project_id}/devices',
      description: 'Nest devices (thermostats, cameras, doorbells) with traits.',
      params: { project_id: { description: 'Device Access project ID', required: true } } },
    { slug: 'get_device', name: 'Get device', risk: 'read', path: '/enterprises/{project_id}/devices/{device_id}',
      description: 'One device with full trait state.',
      params: { project_id: { description: 'Project ID', required: true }, device_id: { description: 'Device ID', required: true } } },
    { slug: 'set_thermostat_temp', name: 'Set thermostat temperature', risk: 'write', method: 'POST', path: '/enterprises/{project_id}/devices/{device_id}:executeCommand',
      description: 'Sets the heat target (°C) on a Nest thermostat in HEAT mode.',
      wrapBody: b => ({ command: 'sdm.devices.commands.ThermostatTemperatureSetpoint.SetHeat', params: { heatCelsius: Number(b.celsius) } }),
      params: { project_id: { description: 'Project ID', required: true }, device_id: { description: 'Device ID', required: true }, celsius: { type: 'number', description: 'Target °C', required: true } } },
  ],
})

export const augustManifest = defineRestConnector({
  slug: 'august',
  name: 'August Smart Lock',
  category: 'Smart Home',
  description: 'Locks — status, lock, and unlock via the August API.',
  baseUrl: 'https://api-production.august.com',
  headers: c => ({ 'x-august-access-token': c.access_token, 'x-august-api-key': c.api_key || '727dba56-fe45-498d-b4aa-293f96aae0e5' }),
  auth: {
    ...apiKeyAuth({ service: 'August', where: 'August app session (access token)', keyHint: 'August has no official public API — tokens are advanced to obtain. Simulate mode is the way to explore this connector.' }),
    fields: [
      { key: 'access_token', label: 'Access token', placeholder: 'Your August session token' },
      { key: 'api_key', label: 'API key (optional)', placeholder: 'Leave blank for default', inputType: 'text' },
    ],
  },
  testPath: '/users/locks/mine',
  testLabel: 'August account connected',
  actions: [
    { slug: 'list_locks', name: 'List locks', risk: 'read', path: '/users/locks/mine',
      description: 'Your locks with house assignment.', params: {} },
    { slug: 'get_lock', name: 'Get lock status', risk: 'read', path: '/locks/{lock_id}',
      description: 'One lock with battery and lock state.',
      params: { lock_id: { description: 'Lock ID', required: true } } },
    { slug: 'lock', name: 'Lock door', risk: 'write', method: 'PUT', path: '/remoteoperate/{lock_id}/lock',
      description: 'Locks the door.',
      params: { lock_id: { description: 'Lock ID', required: true } } },
    { slug: 'unlock', name: 'Unlock door', risk: 'destructive', method: 'PUT', path: '/remoteoperate/{lock_id}/unlock',
      description: 'Unlocks the door — physical security impact. Confirm before using.',
      params: { lock_id: { description: 'Lock ID', required: true } } },
  ],
})

export const opsStrHomeConnectors = [
  opsgenieManifest, freshserviceManifest, jiraServiceManifest, xmattersManifest,
  guestyManifest, hostawayManifest, ownerrezManifest, hostfullyManifest, beds24Manifest,
  philipsHueManifest, smartthingsManifest, ecobeeManifest, googleHomeManifest, augustManifest,
]
