import { defineRestConnector, apiKeyAuth } from '../factory'

// Productivity connectors. Google/Microsoft ones authenticate with a pasted
// OAuth access token (advanced users); everyone else should use Simulate mode
// to try them — the auth hint says so.

const OAUTH_TOKEN_HINT =
  'Advanced: paste an OAuth access token (e.g. from OAuth Playground or your own app). ' +
  'Most people should choose Simulate instead — full functionality, no keys.'

export const airtableManifest = defineRestConnector({
  slug: 'airtable',
  name: 'Airtable',
  category: 'Productivity',
  description: 'Bases, tables, and records — read, create, update, and delete rows.',
  baseUrl: 'https://api.airtable.com/v0',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'Airtable', keyLabel: 'Personal access token', keyPlaceholder: 'pat…', where: 'airtable.com/create/tokens' }),
  testPath: '/meta/bases',
  testLabel: 'Airtable account connected',
  actions: [
    { slug: 'list_bases', name: 'List bases', risk: 'read', path: '/meta/bases',
      description: 'All bases the token can access. Use the base id (app…) in other actions.', params: {} },
    { slug: 'list_tables', name: 'List tables', risk: 'read', path: '/meta/bases/{base_id}/tables',
      description: 'Tables in a base, including field names.',
      params: { base_id: { description: 'Base ID (app…)', required: true } } },
    { slug: 'list_records', name: 'List records', risk: 'read', path: '/{base_id}/{table}', staticQuery: { maxRecords: '50' },
      description: 'Rows from a table. filterByFormula: optional Airtable formula, e.g. {Status}="Open".',
      params: { base_id: { description: 'Base ID (app…)', required: true }, table: { description: 'Table name or ID', required: true }, filterByFormula: { description: 'Airtable filter formula (optional)' } } },
    { slug: 'create_record', name: 'Create record', risk: 'write', method: 'POST', path: '/{base_id}/{table}',
      description: 'Adds a row. fields: object of column name → value.',
      wrapBody: b => ({ fields: b.fields ?? {} }),
      params: { base_id: { description: 'Base ID', required: true }, table: { description: 'Table name or ID', required: true }, fields: { type: 'object', description: 'Column values, e.g. {"Name":"Acme","Status":"Open"}', required: true } } },
    { slug: 'update_record', name: 'Update record', risk: 'write', method: 'PATCH', path: '/{base_id}/{table}/{record_id}',
      description: 'Updates fields on a row.',
      wrapBody: b => ({ fields: b.fields ?? {} }),
      params: { base_id: { description: 'Base ID', required: true }, table: { description: 'Table name or ID', required: true }, record_id: { description: 'Record ID (rec…)', required: true }, fields: { type: 'object', description: 'Column values to change', required: true } } },
    { slug: 'delete_record', name: 'Delete record', risk: 'destructive', method: 'DELETE', path: '/{base_id}/{table}/{record_id}',
      description: 'Permanently deletes a row.',
      params: { base_id: { description: 'Base ID', required: true }, table: { description: 'Table name or ID', required: true }, record_id: { description: 'Record ID (rec…)', required: true } } },
  ],
})

export const asanaManifest = defineRestConnector({
  slug: 'asana',
  name: 'Asana',
  category: 'Productivity',
  description: 'Projects, tasks, and comments via the Asana REST API.',
  baseUrl: 'https://app.asana.com/api/1.0',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'Asana', keyLabel: 'Personal access token', where: 'My Settings → Apps → Developer apps → Personal access tokens' }),
  testPath: '/users/me',
  testLabel: 'Asana account connected',
  actions: [
    { slug: 'list_workspaces', name: 'List workspaces', risk: 'read', path: '/workspaces',
      description: 'Your Asana workspaces. Use the gid in other actions.', params: {} },
    { slug: 'list_projects', name: 'List projects', risk: 'read', path: '/projects',
      description: 'Projects in a workspace.',
      params: { workspace: { description: 'Workspace gid', required: true } } },
    { slug: 'list_tasks', name: 'List tasks in project', risk: 'read', path: '/tasks', staticQuery: { opt_fields: 'name,completed,assignee.name,due_on' },
      description: 'Tasks in a project with assignee and due date.',
      params: { project: { description: 'Project gid', required: true } } },
    { slug: 'get_task', name: 'Get task', risk: 'read', path: '/tasks/{task_gid}',
      description: 'Full details of one task.',
      params: { task_gid: { description: 'Task gid', required: true } } },
    { slug: 'create_task', name: 'Create task', risk: 'write', method: 'POST', path: '/tasks',
      description: 'Creates a task in a project.',
      wrapBody: b => ({ data: { name: b.name, notes: b.notes, projects: [b.project], ...(b.due_on ? { due_on: b.due_on } : {}) } }),
      params: { project: { description: 'Project gid', required: true }, name: { description: 'Task name', required: true }, notes: { description: 'Task description (optional)' }, due_on: { description: 'Due date YYYY-MM-DD (optional)' } } },
    { slug: 'complete_task', name: 'Complete task', risk: 'write', method: 'PUT', path: '/tasks/{task_gid}',
      description: 'Marks a task complete.',
      wrapBody: () => ({ data: { completed: true } }),
      params: { task_gid: { description: 'Task gid', required: true } } },
    { slug: 'add_comment', name: 'Comment on task', risk: 'write', method: 'POST', path: '/tasks/{task_gid}/stories',
      description: 'Adds a comment to a task.',
      wrapBody: b => ({ data: { text: b.text } }),
      params: { task_gid: { description: 'Task gid', required: true }, text: { description: 'Comment text', required: true } } },
  ],
})

export const notionManifest = defineRestConnector({
  slug: 'notion',
  name: 'Notion',
  category: 'Productivity',
  description: 'Search pages, query databases, and create pages via the Notion API.',
  baseUrl: 'https://api.notion.com/v1',
  headers: c => ({ Authorization: `Bearer ${c.api_key}`, 'Notion-Version': '2022-06-28' }),
  auth: apiKeyAuth({ service: 'Notion', keyLabel: 'Internal integration secret', keyPlaceholder: 'ntn_… or secret_…', where: 'notion.so/my-integrations (share target pages with the integration!)' }),
  testPath: '/users/me',
  testLabel: 'Notion workspace connected',
  actions: [
    { slug: 'search', name: 'Search', risk: 'read', method: 'POST', path: '/search',
      description: 'Searches pages and databases shared with the integration.',
      wrapBody: b => ({ query: b.query ?? '', page_size: 20 }),
      params: { query: { description: 'Search text', required: true } } },
    { slug: 'query_database', name: 'Query database', risk: 'read', method: 'POST', path: '/databases/{database_id}/query',
      description: 'Returns rows from a Notion database.',
      wrapBody: () => ({ page_size: 50 }),
      params: { database_id: { description: 'Database ID', required: true } } },
    { slug: 'get_page', name: 'Get page', risk: 'read', path: '/pages/{page_id}',
      description: 'A page\'s properties (not the body blocks).',
      params: { page_id: { description: 'Page ID', required: true } } },
    { slug: 'get_page_content', name: 'Get page content', risk: 'read', path: '/blocks/{page_id}/children', staticQuery: { page_size: '50' },
      description: 'The body blocks (text) of a page.',
      params: { page_id: { description: 'Page ID', required: true } } },
    { slug: 'create_page', name: 'Create page in database', risk: 'write', method: 'POST', path: '/pages',
      description: 'Adds a row/page to a database. title_property is the name of the title column (usually "Name").',
      wrapBody: b => ({ parent: { database_id: b.database_id }, properties: { [String(b.title_property ?? 'Name')]: { title: [{ text: { content: String(b.title ?? 'Untitled') } }] } } }),
      params: { database_id: { description: 'Database ID', required: true }, title: { description: 'Title of the new page', required: true }, title_property: { description: 'Name of the title column (default "Name")' } } },
    { slug: 'list_users', name: 'List users', risk: 'read', path: '/users',
      description: 'Workspace members visible to the integration.', params: {} },
  ],
})

export const trelloManifest = defineRestConnector({
  slug: 'trello',
  name: 'Trello',
  category: 'Productivity',
  description: 'Boards, lists, and cards — read and move work across your Trello boards.',
  baseUrl: 'https://api.trello.com/1',
  headers: c => ({ Authorization: `OAuth oauth_consumer_key="${c.key}", oauth_token="${c.token}"` }),
  auth: {
    ...apiKeyAuth({ service: 'Trello', where: 'trello.com/power-ups/admin → API key' }),
    fields: [
      { key: 'key', label: 'API key', placeholder: 'Your Trello API key', inputType: 'text' },
      { key: 'token', label: 'Token', placeholder: 'Your Trello token', hint: 'Generate from the link next to your API key.' },
    ],
  },
  testPath: '/members/me',
  testLabel: 'Trello account connected',
  actions: [
    { slug: 'list_boards', name: 'List boards', risk: 'read', path: '/members/me/boards', staticQuery: { fields: 'name,url,closed' },
      description: 'Your Trello boards.', params: {} },
    { slug: 'list_lists', name: 'List lists on board', risk: 'read', path: '/boards/{board_id}/lists',
      description: 'Columns (lists) on a board.',
      params: { board_id: { description: 'Board ID', required: true } } },
    { slug: 'list_cards', name: 'List cards in list', risk: 'read', path: '/lists/{list_id}/cards',
      description: 'Cards in a list with names and due dates.',
      params: { list_id: { description: 'List ID', required: true } } },
    { slug: 'create_card', name: 'Create card', risk: 'write', method: 'POST', path: '/cards',
      description: 'Adds a card to a list.',
      params: { idList: { description: 'List ID to add the card to', required: true }, name: { description: 'Card title', required: true }, desc: { description: 'Card description (optional)' } } },
    { slug: 'move_card', name: 'Move card', risk: 'write', method: 'PUT', path: '/cards/{card_id}',
      description: 'Moves a card to another list.',
      params: { card_id: { description: 'Card ID', required: true }, idList: { description: 'Destination list ID', required: true } } },
    { slug: 'add_comment', name: 'Comment on card', risk: 'write', method: 'POST', path: '/cards/{card_id}/actions/comments',
      description: 'Adds a comment to a card.',
      params: { card_id: { description: 'Card ID', required: true }, text: { description: 'Comment text', required: true } } },
    { slug: 'archive_card', name: 'Archive card', risk: 'write', method: 'PUT', path: '/cards/{card_id}',
      description: 'Archives (closes) a card.',
      wrapBody: () => ({ closed: true }),
      params: { card_id: { description: 'Card ID', required: true } } },
  ],
})

export const googleSheetsManifest = defineRestConnector({
  slug: 'google-sheets',
  name: 'Google Sheets',
  category: 'Productivity',
  description: 'Read, append, and update spreadsheet values.',
  baseUrl: 'https://sheets.googleapis.com/v4',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'Google Sheets', keyLabel: 'OAuth access token', keyPlaceholder: 'ya29.…', keyHint: OAUTH_TOKEN_HINT, where: 'Google OAuth (developers.google.com/oauthplayground)' }),
  // Google's public sample sheet — readable by any valid token, 401 otherwise.
  testPath: '/spreadsheets/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms?fields=spreadsheetId',
  testLabel: 'Google Sheets connected',
  actions: [
    { slug: 'get_spreadsheet', name: 'Get spreadsheet info', risk: 'read', path: '/spreadsheets/{spreadsheet_id}', staticQuery: { fields: 'properties.title,sheets.properties' },
      description: 'Spreadsheet title and its sheet (tab) names.',
      params: { spreadsheet_id: { description: 'Spreadsheet ID (from its URL)', required: true } } },
    { slug: 'get_values', name: 'Read values', risk: 'read', path: '/spreadsheets/{spreadsheet_id}/values/{range}',
      description: 'Reads a range, e.g. "Sheet1!A1:D50".',
      params: { spreadsheet_id: { description: 'Spreadsheet ID', required: true }, range: { description: 'A1 range, e.g. Sheet1!A1:D50', required: true } } },
    { slug: 'append_values', name: 'Append rows', risk: 'write', method: 'POST', path: '/spreadsheets/{spreadsheet_id}/values/{range}:append', staticQuery: { valueInputOption: 'USER_ENTERED' },
      description: 'Appends rows after the last row of the range. values: array of row arrays, e.g. [["Acme", 1200]].',
      wrapBody: b => ({ values: b.values ?? [] }),
      params: { spreadsheet_id: { description: 'Spreadsheet ID', required: true }, range: { description: 'A1 range of the table, e.g. Sheet1!A:D', required: true }, values: { type: 'array', description: 'Array of rows (arrays of cell values)', required: true } } },
    { slug: 'update_values', name: 'Update values', risk: 'write', method: 'PUT', path: '/spreadsheets/{spreadsheet_id}/values/{range}', staticQuery: { valueInputOption: 'USER_ENTERED' },
      description: 'Overwrites a range with new values.',
      wrapBody: b => ({ values: b.values ?? [] }),
      params: { spreadsheet_id: { description: 'Spreadsheet ID', required: true }, range: { description: 'A1 range to overwrite', required: true }, values: { type: 'array', description: 'Array of rows', required: true } } },
  ],
})

export const gmailManifest = defineRestConnector({
  slug: 'gmail',
  name: 'Gmail',
  category: 'Productivity',
  description: 'Search, read, and send email via the Gmail API.',
  baseUrl: 'https://gmail.googleapis.com/gmail/v1',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'Gmail', keyLabel: 'OAuth access token', keyPlaceholder: 'ya29.…', keyHint: OAUTH_TOKEN_HINT, where: 'Google OAuth (developers.google.com/oauthplayground)' }),
  testPath: '/users/me/profile',
  testLabel: 'Gmail account connected',
  actions: [
    { slug: 'list_messages', name: 'Search messages', risk: 'read', path: '/users/me/messages', staticQuery: { maxResults: '20' },
      description: 'Searches mail with Gmail syntax, e.g. "from:stripe.com newer_than:7d is:unread".',
      params: { q: { description: 'Gmail search query', required: true } } },
    { slug: 'get_message', name: 'Read message', risk: 'read', path: '/users/me/messages/{message_id}', staticQuery: { format: 'full' },
      description: 'Full content of one message by id.',
      params: { message_id: { description: 'Message ID from search', required: true } } },
    { slug: 'send_email', name: 'Send email', risk: 'write', method: 'POST', path: '/users/me/messages/send',
      description: 'Sends a plain-text email. Confirm with the user before sending.',
      wrapBody: b => ({
        raw: Buffer.from(`To: ${b.to}\r\nSubject: ${b.subject}\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n${b.body ?? ''}`)
          .toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''),
      }),
      params: { to: { description: 'Recipient email address', required: true }, subject: { description: 'Subject line', required: true }, body: { description: 'Plain-text body', required: true } } },
    { slug: 'list_labels', name: 'List labels', risk: 'read', path: '/users/me/labels',
      description: 'Gmail labels (folders).', params: {} },
    { slug: 'trash_message', name: 'Trash message', risk: 'destructive', method: 'POST', path: '/users/me/messages/{message_id}/trash',
      description: 'Moves a message to Trash.',
      params: { message_id: { description: 'Message ID', required: true } } },
  ],
})

export const googleCalendarManifest = defineRestConnector({
  slug: 'google-calendar',
  name: 'Google Calendar',
  category: 'Productivity',
  description: 'List, create, and delete calendar events.',
  baseUrl: 'https://www.googleapis.com/calendar/v3',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'Google Calendar', keyLabel: 'OAuth access token', keyPlaceholder: 'ya29.…', keyHint: OAUTH_TOKEN_HINT, where: 'Google OAuth (developers.google.com/oauthplayground)' }),
  testPath: '/users/me/calendarList?maxResults=1',
  testLabel: 'Google Calendar connected',
  actions: [
    { slug: 'list_calendars', name: 'List calendars', risk: 'read', path: '/users/me/calendarList',
      description: 'Your calendars. Use "primary" as calendar_id for the main one.', params: {} },
    { slug: 'list_events', name: 'List events', risk: 'read', path: '/calendars/{calendar_id}/events', staticQuery: { singleEvents: 'true', orderBy: 'startTime', maxResults: '25' },
      description: 'Upcoming events. timeMin: ISO datetime to start from (e.g. now).',
      params: { calendar_id: { description: 'Calendar ID ("primary" for main)', required: true }, timeMin: { description: 'ISO start, e.g. 2026-07-02T00:00:00Z' } } },
    { slug: 'create_event', name: 'Create event', risk: 'write', method: 'POST', path: '/calendars/{calendar_id}/events',
      description: 'Creates an event with start/end ISO datetimes.',
      wrapBody: b => ({ summary: b.summary, ...(b.description ? { description: b.description } : {}), start: { dateTime: b.start }, end: { dateTime: b.end } }),
      params: { calendar_id: { description: 'Calendar ID ("primary")', required: true }, summary: { description: 'Event title', required: true }, start: { description: 'Start ISO datetime', required: true }, end: { description: 'End ISO datetime', required: true }, description: { description: 'Event notes (optional)' } } },
    { slug: 'delete_event', name: 'Delete event', risk: 'destructive', method: 'DELETE', path: '/calendars/{calendar_id}/events/{event_id}',
      description: 'Deletes an event.',
      params: { calendar_id: { description: 'Calendar ID', required: true }, event_id: { description: 'Event ID', required: true } } },
  ],
})

export const outlookManifest = defineRestConnector({
  slug: 'outlook',
  name: 'Microsoft Outlook',
  category: 'Productivity',
  description: 'Mail, calendar, and contacts via Microsoft Graph.',
  baseUrl: 'https://graph.microsoft.com/v1.0',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'Microsoft 365', keyLabel: 'OAuth access token', keyPlaceholder: 'eyJ…', keyHint: OAUTH_TOKEN_HINT, where: 'Microsoft Graph OAuth (developer.microsoft.com/graph/graph-explorer)' }),
  testPath: '/me',
  testLabel: 'Microsoft account connected',
  actions: [
    { slug: 'list_messages', name: 'List recent mail', risk: 'read', path: '/me/messages', staticQuery: { $top: '20', $orderby: 'receivedDateTime desc', $select: 'subject,from,receivedDateTime,isRead,bodyPreview' },
      description: 'Most recent messages in the inbox.', params: {} },
    { slug: 'search_messages', name: 'Search mail', risk: 'read', path: '/me/messages', staticQuery: { $top: '20' },
      description: 'Searches mail. $search syntax, e.g. "from:contoso subject:invoice".',
      params: { $search: { description: 'Search terms', required: true } } },
    { slug: 'send_mail', name: 'Send email', risk: 'write', method: 'POST', path: '/me/sendMail',
      description: 'Sends a plain-text email. Confirm with the user before sending.',
      wrapBody: b => ({ message: { subject: b.subject, body: { contentType: 'Text', content: b.body ?? '' }, toRecipients: [{ emailAddress: { address: b.to } }] } }),
      params: { to: { description: 'Recipient email', required: true }, subject: { description: 'Subject', required: true }, body: { description: 'Plain-text body', required: true } } },
    { slug: 'list_events', name: 'List calendar events', risk: 'read', path: '/me/calendar/events', staticQuery: { $top: '25', $orderby: 'start/dateTime', $select: 'subject,start,end,location,organizer' },
      description: 'Events on the default calendar.', params: {} },
    { slug: 'create_event', name: 'Create event', risk: 'write', method: 'POST', path: '/me/events',
      description: 'Creates a calendar event (UTC ISO datetimes).',
      wrapBody: b => ({ subject: b.subject, start: { dateTime: b.start, timeZone: 'UTC' }, end: { dateTime: b.end, timeZone: 'UTC' } }),
      params: { subject: { description: 'Event title', required: true }, start: { description: 'Start ISO datetime', required: true }, end: { description: 'End ISO datetime', required: true } } },
    { slug: 'list_contacts', name: 'List contacts', risk: 'read', path: '/me/contacts', staticQuery: { $top: '30', $select: 'displayName,emailAddresses,companyName' },
      description: 'Your Outlook contacts.', params: {} },
  ],
})

export const productivityConnectors = [
  airtableManifest, asanaManifest, notionManifest, trelloManifest,
  googleSheetsManifest, gmailManifest, googleCalendarManifest, outlookManifest,
]
