import { defineRestConnector, apiKeyAuth, basicAuth } from '../factory'

// Security connectors A — SIEM & log platforms + EDR/XDR.

export const splunkManifest = defineRestConnector({
  slug: 'splunk',
  name: 'Splunk',
  category: 'Security',
  description: 'Run searches, list indexes, and check fired alerts via the Splunk REST API.',
  baseUrl: c => c.host,
  formEncoded: true,
  headers: c => ({ Authorization: `Bearer ${c.token}` }),
  auth: {
    ...apiKeyAuth({ service: 'Splunk', where: 'Settings → Tokens (Splunk Enterprise 8+ / Cloud)' }),
    fields: [
      { key: 'host', label: 'Management URL', placeholder: 'https://yourstack.splunkcloud.com:8089', inputType: 'text' },
      { key: 'token', label: 'Authentication token', placeholder: 'Your Splunk token' },
    ],
  },
  testPath: '/services/server/info?output_mode=json',
  testLabel: 'Splunk instance connected',
  actions: [
    { slug: 'run_search', name: 'Run search', risk: 'read', method: 'POST', path: '/services/search/jobs/export', staticQuery: { output_mode: 'json' },
      description: 'Runs an SPL search and streams results, e.g. "search index=main error | head 20". earliest: e.g. -24h (optional).',
      wrapBody: b => ({ search: String(b.search).startsWith('search') || String(b.search).startsWith('|') ? b.search : `search ${b.search}`, earliest_time: b.earliest ?? '-24h', output_mode: 'json' }),
      params: { search: { description: 'SPL query', required: true }, earliest: { description: 'Earliest time, e.g. -24h (default)' } } },
    { slug: 'list_indexes', name: 'List indexes', risk: 'read', path: '/services/data/indexes', staticQuery: { output_mode: 'json', count: '30' },
      description: 'Data indexes with event counts.', params: {} },
    { slug: 'list_saved_searches', name: 'List saved searches', risk: 'read', path: '/services/saved/searches', staticQuery: { output_mode: 'json', count: '30' },
      description: 'Saved searches / reports / alerts.', params: {} },
    { slug: 'list_fired_alerts', name: 'List fired alerts', risk: 'read', path: '/services/alerts/fired_alerts', staticQuery: { output_mode: 'json' },
      description: 'Alerts that have fired recently.', params: {} },
  ],
})

export const microsoftSentinelManifest = defineRestConnector({
  slug: 'microsoft-sentinel',
  name: 'Microsoft Sentinel',
  category: 'Security',
  description: 'Incidents and analytics rules via the Microsoft Sentinel management API.',
  baseUrl: c => `https://management.azure.com/subscriptions/${c.subscription_id}/resourceGroups/${c.resource_group}/providers/Microsoft.OperationalInsights/workspaces/${c.workspace_name}/providers/Microsoft.SecurityInsights`,
  headers: c => ({ Authorization: `Bearer ${c.access_token}` }),
  auth: {
    ...apiKeyAuth({ service: 'Microsoft Sentinel', where: 'Azure AD app registration (ARM token)' }),
    fields: [
      { key: 'access_token', label: 'Azure ARM access token', placeholder: 'eyJ…', hint: 'Advanced — most people should use Simulate mode.' },
      { key: 'subscription_id', label: 'Subscription ID', placeholder: 'GUID', inputType: 'text' },
      { key: 'resource_group', label: 'Resource group', placeholder: 'rg-security', inputType: 'text' },
      { key: 'workspace_name', label: 'Log Analytics workspace', placeholder: 'sentinel-workspace', inputType: 'text' },
    ],
  },
  testPath: '/incidents?api-version=2023-02-01&$top=1',
  testLabel: 'Sentinel workspace connected',
  actions: [
    { slug: 'list_incidents', name: 'List incidents', risk: 'read', path: '/incidents', staticQuery: { 'api-version': '2023-02-01', $top: '25', $orderby: 'properties/createdTimeUtc desc' },
      description: 'Sentinel incidents with severity and status.', params: {} },
    { slug: 'get_incident', name: 'Get incident', risk: 'read', path: '/incidents/{incident_id}', staticQuery: { 'api-version': '2023-02-01' },
      description: 'One incident with full properties.',
      params: { incident_id: { description: 'Incident GUID', required: true } } },
    { slug: 'list_incident_alerts', name: 'List incident alerts', risk: 'read', method: 'POST', path: '/incidents/{incident_id}/alerts', staticQuery: { 'api-version': '2023-02-01' },
      description: 'Alerts grouped under an incident.',
      params: { incident_id: { description: 'Incident GUID', required: true } } },
    { slug: 'list_alert_rules', name: 'List analytics rules', risk: 'read', path: '/alertRules', staticQuery: { 'api-version': '2023-02-01' },
      description: 'Detection (analytics) rules and their enabled state.', params: {} },
  ],
})

export const ibmQradarManifest = defineRestConnector({
  slug: 'ibm-qradar',
  name: 'IBM QRadar',
  category: 'Security',
  description: 'Offenses, rules, and AQL searches via the QRadar REST API.',
  baseUrl: c => c.host,
  headers: c => ({ SEC: c.token, Version: '20.0' }),
  auth: {
    ...apiKeyAuth({ service: 'IBM QRadar', where: 'Admin → Authorized Services (SEC token)' }),
    fields: [
      { key: 'host', label: 'Console URL', placeholder: 'https://qradar.yourcompany.com', inputType: 'text' },
      { key: 'token', label: 'SEC token', placeholder: 'Authorized service token' },
    ],
  },
  testPath: '/api/system/about',
  testLabel: 'QRadar console connected',
  actions: [
    { slug: 'list_offenses', name: 'List offenses', risk: 'read', path: '/api/siem/offenses', staticQuery: { sort: '-start_time' },
      description: 'Offenses with magnitude and status. filter: e.g. status=OPEN (optional).',
      params: { filter: { description: 'QRadar filter, e.g. status=OPEN (optional)' } } },
    { slug: 'get_offense', name: 'Get offense', risk: 'read', path: '/api/siem/offenses/{offense_id}',
      description: 'One offense with source/destination details.',
      params: { offense_id: { type: 'integer', description: 'Offense ID', required: true } } },
    { slug: 'close_offense', name: 'Close offense', risk: 'write', method: 'POST', path: '/api/siem/offenses/{offense_id}', staticQuery: { status: 'CLOSED', closing_reason_id: '1' },
      description: 'Closes an offense (reason: non-issue).',
      params: { offense_id: { type: 'integer', description: 'Offense ID', required: true } } },
    { slug: 'run_aql_search', name: 'Run AQL search', risk: 'read', method: 'POST', path: '/api/ariel/searches?query_expression={query}',
      description: 'Starts an AQL search, e.g. "SELECT sourceip, destinationip FROM events LAST 1 HOURS". Returns a search_id — poll with get_search_results.',
      params: { query: { description: 'AQL query', required: true } } },
    { slug: 'get_search_results', name: 'Get AQL results', risk: 'read', path: '/api/ariel/searches/{search_id}/results',
      description: 'Results of a completed AQL search.',
      params: { search_id: { description: 'Search ID from run_aql_search', required: true } } },
  ],
})

export const elasticSiemManifest = defineRestConnector({
  slug: 'elastic-siem',
  name: 'Elastic SIEM',
  category: 'Security',
  description: 'Detection rules and alert signals via the Elastic Security (Kibana) API.',
  baseUrl: c => c.kibana_url,
  headers: c => ({ Authorization: `ApiKey ${c.api_key}`, 'kbn-xsrf': 'true' }),
  auth: {
    ...apiKeyAuth({ service: 'Elastic', where: 'Kibana → Stack Management → API Keys' }),
    fields: [
      { key: 'kibana_url', label: 'Kibana URL', placeholder: 'https://yourdeploy.kb.us-east-1.aws.found.io', inputType: 'text' },
      { key: 'api_key', label: 'API key (base64)', placeholder: 'Your Elastic API key' },
    ],
  },
  testPath: '/api/status',
  testLabel: 'Elastic deployment connected',
  actions: [
    { slug: 'list_detection_rules', name: 'List detection rules', risk: 'read', path: '/api/detection_engine/rules/_find', staticQuery: { per_page: '30', sort_field: 'enabled', sort_order: 'desc' },
      description: 'Detection rules with enabled state and severity.', params: {} },
    { slug: 'search_alerts', name: 'Search alert signals', risk: 'read', method: 'POST', path: '/api/detection_engine/signals/search',
      description: 'Alert signals from the last N hours (default 24).',
      wrapBody: b => ({ query: { bool: { filter: [{ range: { '@timestamp': { gte: `now-${Number(b.hours ?? 24)}h` } } }] } }, size: 25, sort: [{ '@timestamp': 'desc' }] }),
      params: { hours: { type: 'integer', description: 'Look-back window in hours (default 24)' } } },
    { slug: 'update_alert_status', name: 'Update alert status', risk: 'write', method: 'POST', path: '/api/detection_engine/signals/status',
      description: 'Sets alert signals to open, acknowledged, or closed.',
      wrapBody: b => ({ signal_ids: [b.signal_id], status: b.status }),
      params: { signal_id: { description: 'Signal (alert) ID', required: true }, status: { description: 'open | acknowledged | closed', required: true, enum: ['open', 'acknowledged', 'closed'] } } },
  ],
})

export const sumoLogicManifest = defineRestConnector({
  slug: 'sumo-logic',
  name: 'Sumo Logic',
  category: 'Security',
  description: 'Collectors and log search jobs via the Sumo Logic API.',
  baseUrl: c => `https://api.${c.deployment || 'us2'}.sumologic.com/api/v1`,
  headers: c => ({ Authorization: basicAuth(c.access_id, c.access_key) }),
  auth: {
    ...apiKeyAuth({ service: 'Sumo Logic', where: 'Administration → Security → Access Keys' }),
    fields: [
      { key: 'access_id', label: 'Access ID', placeholder: 'su…', inputType: 'text' },
      { key: 'access_key', label: 'Access key', placeholder: 'Your access key' },
      { key: 'deployment', label: 'Deployment', placeholder: 'us1 | us2 | eu | au (default us2)', inputType: 'text' },
    ],
  },
  testPath: '/collectors?limit=1',
  testLabel: 'Sumo Logic connected',
  actions: [
    { slug: 'list_collectors', name: 'List collectors', risk: 'read', path: '/collectors', staticQuery: { limit: '30' },
      description: 'Data collectors and their status.', params: {} },
    { slug: 'create_search_job', name: 'Start search job', risk: 'read', method: 'POST', path: '/search/jobs',
      description: 'Starts a log search. Returns an id — poll get_search_job, then fetch results.',
      wrapBody: b => ({ query: b.query, from: b.from ?? new Date(Date.now() - 24 * 3600e3).toISOString(), to: b.to ?? new Date().toISOString(), timeZone: 'UTC' }),
      params: { query: { description: 'Sumo query, e.g. error | count by _sourceCategory', required: true }, from: { description: 'ISO start (default 24h ago)' }, to: { description: 'ISO end (default now)' } } },
    { slug: 'get_search_job', name: 'Get search job status', risk: 'read', path: '/search/jobs/{search_job_id}',
      description: 'State of a search job (GATHERING RESULTS → DONE GATHERING RESULTS).',
      params: { search_job_id: { description: 'Job ID from create_search_job', required: true } } },
    { slug: 'get_search_results', name: 'Get search results', risk: 'read', path: '/search/jobs/{search_job_id}/messages', staticQuery: { offset: '0', limit: '25' },
      description: 'Messages from a completed search job.',
      params: { search_job_id: { description: 'Job ID', required: true } } },
  ],
})

export const logrhythmManifest = defineRestConnector({
  slug: 'logrhythm',
  name: 'LogRhythm',
  category: 'Security',
  description: 'Alarms and cases via the LogRhythm REST API.',
  baseUrl: c => c.host,
  headers: c => ({ Authorization: `Bearer ${c.token}` }),
  auth: {
    ...apiKeyAuth({ service: 'LogRhythm', where: 'Client Console → Administration → API tokens' }),
    fields: [
      { key: 'host', label: 'Platform Manager URL', placeholder: 'https://logrhythm.yourcompany.com:8501', inputType: 'text' },
      { key: 'token', label: 'API token', placeholder: 'Your LogRhythm token' },
    ],
  },
  testPath: '/lr-alarm-api/alarms?count=1',
  testLabel: 'LogRhythm connected',
  actions: [
    { slug: 'list_alarms', name: 'List alarms', risk: 'read', path: '/lr-alarm-api/alarms', staticQuery: { count: '25', orderBy: 'DateInserted', dir: 'descending' },
      description: 'Recent alarms with status and risk.', params: {} },
    { slug: 'get_alarm', name: 'Get alarm', risk: 'read', path: '/lr-alarm-api/alarms/{alarm_id}',
      description: 'One alarm with details.',
      params: { alarm_id: { type: 'integer', description: 'Alarm ID', required: true } } },
    { slug: 'update_alarm_status', name: 'Update alarm status', risk: 'write', method: 'PATCH', path: '/lr-alarm-api/alarms/{alarm_id}',
      description: 'Sets alarm status, e.g. Opened, Working, Escalated, Closed_FalseAlarm, Closed_Resolved.',
      wrapBody: b => ({ alarmStatus: b.status }),
      params: { alarm_id: { type: 'integer', description: 'Alarm ID', required: true }, status: { description: 'New status', required: true } } },
    { slug: 'list_cases', name: 'List cases', risk: 'read', path: '/lr-case-api/cases', staticQuery: { count: '25' },
      description: 'Investigation cases.', params: {} },
    { slug: 'create_case', name: 'Create case', risk: 'write', method: 'POST', path: '/lr-case-api/cases',
      description: 'Opens a case. priority 1 (highest) – 5.',
      wrapBody: b => ({ name: b.name, priority: Number(b.priority ?? 3), summary: b.summary ?? '' }),
      params: { name: { description: 'Case name', required: true }, priority: { type: 'integer', description: '1–5 (default 3)' }, summary: { description: 'Case summary (optional)' } } },
  ],
})

export const carbonBlackManifest = defineRestConnector({
  slug: 'carbon-black',
  name: 'VMware Carbon Black',
  category: 'Security',
  description: 'Alerts, devices, and quarantine via the Carbon Black Cloud API.',
  baseUrl: c => c.host,
  headers: c => ({ 'X-Auth-Token': `${c.api_secret}/${c.api_id}` }),
  auth: {
    ...apiKeyAuth({ service: 'Carbon Black Cloud', where: 'Settings → API Access' }),
    fields: [
      { key: 'host', label: 'Dashboard URL', placeholder: 'https://defense.conferdeploy.net', inputType: 'text' },
      { key: 'org_key', label: 'Org key', placeholder: 'e.g. ABCD1234', inputType: 'text' },
      { key: 'api_id', label: 'API ID', placeholder: 'API key ID', inputType: 'text' },
      { key: 'api_secret', label: 'API secret key', placeholder: 'API secret' },
    ],
  },
  testPath: '/integrationServices/v3/cblr/session',
  testLabel: 'Carbon Black Cloud connected',
  actions: [
    { slug: 'search_alerts', name: 'Search alerts', risk: 'read', method: 'POST', path: '/api/alerts/v7/orgs/{org_key}/alerts/_search',
      description: 'Recent alerts sorted by severity.',
      wrapBody: () => ({ rows: 25, sort: [{ field: 'severity', order: 'DESC' }], criteria: {} }),
      params: { org_key: { description: 'Your org key', required: true } } },
    { slug: 'search_devices', name: 'Search devices', risk: 'read', method: 'POST', path: '/appservices/v6/orgs/{org_key}/devices/_search',
      description: 'Endpoints with status and last check-in.',
      wrapBody: () => ({ rows: 25, criteria: {} }),
      params: { org_key: { description: 'Your org key', required: true } } },
    { slug: 'quarantine_device', name: 'Quarantine device', risk: 'destructive', method: 'POST', path: '/appservices/v6/orgs/{org_key}/device_actions',
      description: 'Network-isolates a device. Confirm before using.',
      wrapBody: b => ({ action_type: 'QUARANTINE', device_id: [Number(b.device_id)], options: { toggle: 'ON' } }),
      params: { org_key: { description: 'Your org key', required: true }, device_id: { type: 'integer', description: 'Device ID', required: true } } },
    { slug: 'unquarantine_device', name: 'Lift quarantine', risk: 'write', method: 'POST', path: '/appservices/v6/orgs/{org_key}/device_actions',
      description: 'Restores network access for a quarantined device.',
      wrapBody: b => ({ action_type: 'QUARANTINE', device_id: [Number(b.device_id)], options: { toggle: 'OFF' } }),
      params: { org_key: { description: 'Your org key', required: true }, device_id: { type: 'integer', description: 'Device ID', required: true } } },
  ],
})

export const cortexXdrManifest = defineRestConnector({
  slug: 'cortex-xdr',
  name: 'Cortex XDR',
  category: 'Security',
  description: 'Incidents, endpoints, and isolation via the Cortex XDR API.',
  baseUrl: c => c.api_url,
  headers: c => ({ 'x-xdr-auth-id': c.auth_id, Authorization: c.api_key }),
  auth: {
    ...apiKeyAuth({ service: 'Cortex XDR', where: 'Settings → Configurations → API Keys (Standard key)' }),
    fields: [
      { key: 'api_url', label: 'API URL', placeholder: 'https://api-yourtenant.xdr.us.paloaltonetworks.com', inputType: 'text' },
      { key: 'auth_id', label: 'API key ID', placeholder: 'e.g. 1', inputType: 'text' },
      { key: 'api_key', label: 'API key', placeholder: 'Your Cortex XDR key' },
    ],
  },
  testPath: '/public_api/v1/healthcheck',
  testLabel: 'Cortex XDR tenant connected',
  actions: [
    { slug: 'get_incidents', name: 'List incidents', risk: 'read', method: 'POST', path: '/public_api/v1/incidents/get_incidents',
      description: 'Recent incidents sorted by creation time.',
      wrapBody: () => ({ request_data: { search_from: 0, search_to: 25, sort: { field: 'creation_time', keyword: 'desc' } } }),
      params: {} },
    { slug: 'get_endpoints', name: 'List endpoints', risk: 'read', method: 'POST', path: '/public_api/v1/endpoints/get_endpoint',
      description: 'Endpoints with status and OS.',
      wrapBody: () => ({ request_data: { search_from: 0, search_to: 25 } }),
      params: {} },
    { slug: 'isolate_endpoint', name: 'Isolate endpoint', risk: 'destructive', method: 'POST', path: '/public_api/v1/endpoints/isolate',
      description: 'Network-isolates an endpoint. Confirm before using.',
      wrapBody: b => ({ request_data: { endpoint_id: b.endpoint_id } }),
      params: { endpoint_id: { description: 'Endpoint ID', required: true } } },
    { slug: 'unisolate_endpoint', name: 'Un-isolate endpoint', risk: 'write', method: 'POST', path: '/public_api/v1/endpoints/unisolate',
      description: 'Restores network access to an isolated endpoint.',
      wrapBody: b => ({ request_data: { endpoint_id: b.endpoint_id } }),
      params: { endpoint_id: { description: 'Endpoint ID', required: true } } },
  ],
})

export const oktaManifest = defineRestConnector({
  slug: 'okta',
  name: 'Okta',
  category: 'Security',
  description: 'Users, groups, apps, and system log via the Okta API.',
  baseUrl: c => `https://${c.org_domain}`,
  headers: c => ({ Authorization: `SSWS ${c.api_key}` }),
  auth: {
    ...apiKeyAuth({ service: 'Okta', where: 'Security → API → Tokens' }),
    fields: [
      { key: 'org_domain', label: 'Okta domain', placeholder: 'yourcompany.okta.com', inputType: 'text' },
      { key: 'api_key', label: 'API token', placeholder: '00…' },
    ],
  },
  testPath: '/api/v1/users/me',
  testLabel: 'Okta org connected',
  actions: [
    { slug: 'list_users', name: 'List users', risk: 'read', path: '/api/v1/users', staticQuery: { limit: '25' },
      description: 'Users with status. q: name/email search (optional).',
      params: { q: { description: 'Search text (optional)' } } },
    { slug: 'get_user', name: 'Get user', risk: 'read', path: '/api/v1/users/{user_id}',
      description: 'One user by ID or login email.',
      params: { user_id: { description: 'User ID or login email', required: true } } },
    { slug: 'suspend_user', name: 'Suspend user', risk: 'destructive', method: 'POST', path: '/api/v1/users/{user_id}/lifecycle/suspend',
      description: 'Suspends a user (blocks sign-in). Confirm before using.',
      params: { user_id: { description: 'User ID', required: true } } },
    { slug: 'unsuspend_user', name: 'Unsuspend user', risk: 'write', method: 'POST', path: '/api/v1/users/{user_id}/lifecycle/unsuspend',
      description: 'Restores a suspended user.',
      params: { user_id: { description: 'User ID', required: true } } },
    { slug: 'reset_password', name: 'Send password reset', risk: 'write', method: 'POST', path: '/api/v1/users/{user_id}/lifecycle/reset_password', staticQuery: { sendEmail: 'true' },
      description: 'Emails the user a password-reset link.',
      params: { user_id: { description: 'User ID', required: true } } },
    { slug: 'list_groups', name: 'List groups', risk: 'read', path: '/api/v1/groups', staticQuery: { limit: '30' },
      description: 'Okta groups.', params: {} },
    { slug: 'list_apps', name: 'List applications', risk: 'read', path: '/api/v1/apps', staticQuery: { limit: '30' },
      description: 'Integrated applications.', params: {} },
    { slug: 'list_system_log', name: 'System log events', risk: 'read', path: '/api/v1/logs', staticQuery: { limit: '50' },
      description: 'Recent auth/system events. q: filter text (optional).',
      params: { q: { description: 'Filter text (optional)' } } },
  ],
})

export const azureAdManifest = defineRestConnector({
  slug: 'azure-ad',
  name: 'Azure Active Directory',
  category: 'Security',
  description: 'Users, groups, and sign-in logs via Microsoft Graph (Entra ID).',
  baseUrl: 'https://graph.microsoft.com/v1.0',
  headers: c => ({ Authorization: `Bearer ${c.api_key}` }),
  auth: apiKeyAuth({ service: 'Microsoft Entra ID', keyLabel: 'Graph access token', keyPlaceholder: 'eyJ…', where: 'Azure AD app registration (Graph token)', keyHint: 'Advanced — most people should use Simulate mode.' }),
  testPath: '/organization?$top=1',
  testLabel: 'Entra ID tenant connected',
  actions: [
    { slug: 'list_users', name: 'List users', risk: 'read', path: '/users', staticQuery: { $top: '25', $select: 'displayName,userPrincipalName,accountEnabled,jobTitle' },
      description: 'Directory users with enabled state.', params: {} },
    { slug: 'get_user', name: 'Get user', risk: 'read', path: '/users/{user_id}',
      description: 'One user by ID or userPrincipalName.',
      params: { user_id: { description: 'User ID or UPN (email)', required: true } } },
    { slug: 'list_signins', name: 'List sign-in logs', risk: 'read', path: '/auditLogs/signIns', staticQuery: { $top: '25' },
      description: 'Recent sign-ins with status, location, and risk.', params: {} },
    { slug: 'list_groups', name: 'List groups', risk: 'read', path: '/groups', staticQuery: { $top: '30', $select: 'displayName,mail,securityEnabled' },
      description: 'Directory groups.', params: {} },
    { slug: 'revoke_sessions', name: 'Revoke user sessions', risk: 'destructive', method: 'POST', path: '/users/{user_id}/revokeSignInSessions',
      description: 'Signs the user out everywhere (invalidates refresh tokens). Confirm before using.',
      params: { user_id: { description: 'User ID or UPN', required: true } } },
    { slug: 'disable_user', name: 'Disable user', risk: 'destructive', method: 'PATCH', path: '/users/{user_id}',
      description: 'Blocks sign-in for a user. Confirm before using.',
      wrapBody: () => ({ accountEnabled: false }),
      params: { user_id: { description: 'User ID or UPN', required: true } } },
  ],
})

export const duoSecurityManifest = defineRestConnector({
  slug: 'duo-security',
  name: 'Duo Security',
  category: 'Security',
  description: 'Users, devices, and auth logs from Duo (MFA).',
  baseUrl: c => `https://${c.api_hostname}`,
  headers: c => ({ Authorization: basicAuth(c.integration_key, c.secret_key) }),
  auth: {
    ...apiKeyAuth({ service: 'Duo', where: 'Admin Panel → Applications → Admin API', keyHint: 'Note: Duo\'s API uses HMAC-signed requests that need advanced setup — Simulate mode is the way to explore this connector.' }),
    fields: [
      { key: 'api_hostname', label: 'API hostname', placeholder: 'api-xxxxxxxx.duosecurity.com', inputType: 'text' },
      { key: 'integration_key', label: 'Integration key', placeholder: 'DI…', inputType: 'text' },
      { key: 'secret_key', label: 'Secret key', placeholder: 'Your Duo secret key' },
    ],
  },
  testPath: '/admin/v1/info/summary',
  testLabel: 'Duo account connected',
  actions: [
    { slug: 'list_users', name: 'List users', risk: 'read', path: '/admin/v1/users', staticQuery: { limit: '25' },
      description: 'Duo-enrolled users with status.', params: {} },
    { slug: 'list_phones', name: 'List phones', risk: 'read', path: '/admin/v1/phones', staticQuery: { limit: '25' },
      description: 'Enrolled devices.', params: {} },
    { slug: 'list_auth_logs', name: 'Authentication logs', risk: 'read', path: '/admin/v2/logs/authentication', staticQuery: { limit: '25' },
      description: 'Recent MFA authentications with result and factor.', params: {} },
    { slug: 'get_account_summary', name: 'Account summary', risk: 'read', path: '/admin/v1/info/summary',
      description: 'User/phone/integration counts.', params: {} },
  ],
})

export const securityAConnectors = [
  splunkManifest, microsoftSentinelManifest, ibmQradarManifest, elasticSiemManifest,
  sumoLogicManifest, logrhythmManifest, carbonBlackManifest, cortexXdrManifest,
  oktaManifest, azureAdManifest, duoSecurityManifest,
]
