export interface ConnectorExamples {
  chatPhrases: string[]
  automations: { name: string; description: string }[]
}

export const CONNECTOR_EXAMPLES: Record<string, ConnectorExamples> = {
  slack: {
    chatPhrases: [
      'Send a message to #general saying "Deployment complete"',
      'Post a rich alert card to #ops-alerts with title "High CPU" and level warning',
      'List all channels in our Slack workspace',
      'Schedule a message to #engineering for tomorrow at 9 AM: "Standup time!"',
      'Search Slack for messages mentioning "API outage" in the last 24 hours',
      'Add a 👀 reaction to the last message in #incidents',
      'Create a new private channel called "incident-2025-06"',
      'Post a table card to #reporting with headers "Host,Status,Score" and 3 rows',
    ],
    automations: [
      { name: 'Daily Standup Summary', description: 'Post a morning standup prompt to #engineering every weekday at 9 AM' },
      { name: 'Incident Bridge', description: 'When a PagerDuty alert fires, create a Slack thread in #incidents with full alert details and invite the on-call' },
      { name: 'Deployment Announcements', description: 'Post release notes to #product-updates whenever a deployment completes' },
      { name: 'Weekly KPI Digest', description: 'Every Friday, compile and post key metrics to #leadership-updates as a rich facts card' },
    ],
  },
  pagerduty: {
    chatPhrases: [
      'List all active incidents in PagerDuty',
      'Show me high-urgency incidents right now',
      'Acknowledge incident P1234567',
      'Who is on call for the security team right now?',
      'Create a PagerDuty incident: title "Database down", urgency high',
      'List all escalation policies',
      'Snooze incident INC001 for 2 hours',
      'Add a note to incident P9876543: "Root cause identified — rolling back deployment"',
      'Get all log entries for incident P1234567',
    ],
    automations: [
      { name: 'Critical Incident Escalation', description: 'If an incident stays unacknowledged for 10 minutes, escalate to the secondary on-call and post to #incidents' },
      { name: 'Incident Summary Report', description: 'Every Monday, generate a summary of last week\'s incidents with MTTR and post to #ops' },
      { name: 'Quiet Hours Guard', description: 'Between 11 PM and 7 AM, only page for critical severity — auto-suppress low/medium alerts' },
      { name: 'Post-Incident Reminder', description: 'After an incident resolves, remind the on-call to file a post-mortem within 48 hours' },
    ],
  },
  crowdstrike: {
    chatPhrases: [
      'List all open detections in CrowdStrike',
      'Show me high severity detections from the last 24 hours',
      'Contain endpoint HOST-12345 in CrowdStrike',
      'Search for hosts with "Windows Server 2019" in their OS',
      'List all IOCs of type sha256 in CrowdStrike',
      'Create an IOC to block domain "evil.example.com"',
      'List open incidents in CrowdStrike Falcon',
      'Show me all CVEs for host LAPTOP-ABC',
      'Update detection ID xyz to status "in_progress" and assign to analyst@company.com',
    ],
    automations: [
      { name: 'Daily Security Briefing', description: 'Every morning, pull open detections, list unresolved high-severity events, and post a summary to #security-ops' },
      { name: 'Auto-Contain on Critical', description: 'When a critical detection fires, automatically contain the affected endpoint and open a PagerDuty incident' },
      { name: 'Stale Endpoint Alert', description: 'Weekly scan for hosts offline more than 14 days — report to the security team for deprovisioning' },
      { name: 'Detection → Ticket Pipeline', description: 'For each new high-severity detection, create a ServiceNow incident ticket with full detection context' },
    ],
  },
  sentinelone: {
    chatPhrases: [
      'List active threats in SentinelOne',
      'Show me all threats from the last 48 hours',
      'Isolate agent AGENT-001 from the network',
      'Mitigate threat ID 123456 with quarantine action',
      'Mark threat 789 as benign',
      'Initiate a scan on endpoint LAPTOP-XYZ',
      'List all agent groups in SentinelOne',
      'List recent exclusions',
      'Add a path exclusion for C:\\Tools\\Internal\\app.exe',
      'Fetch logs for agent AGENT-001',
    ],
    automations: [
      { name: 'Threat Response Workflow', description: 'On a new Threat event, isolate the agent, notify the SOC via Slack, and create a ticket in ServiceNow' },
      { name: 'Morning Threat Digest', description: 'Every day at 8 AM, compile all active threats by severity and send to #security-alerts' },
      { name: 'Reconnect After Clearance', description: 'After a threat is mitigated and cleared, auto-reconnect the isolated agent and update the ticket to resolved' },
      { name: 'Agent Health Monitor', description: 'Check agent connectivity daily — alert on any agents offline or not reporting for 12+ hours' },
    ],
  },
  sophos: {
    chatPhrases: [
      'List active alerts in Sophos Central',
      'Show me all endpoints with high severity alerts',
      'Isolate endpoint LAPTOP-JOHN from the network',
      'List quarantined items in Sophos',
      'Toggle tamper protection off on LAPTOP-JOHN and get the uninstall password',
      'List all allowed items in Sophos',
      'Add a SHA-256 hash to the allow list: abc123...',
      'Show recent SIEM events from Sophos',
      'Get threat details for endpoint WORKSTATION-001',
    ],
    automations: [
      { name: 'Endpoint Isolation on Alert', description: 'When a critical Sophos alert fires, isolate the endpoint, alert the security team, and log to audit' },
      { name: 'Daily Endpoint Health Check', description: 'Every morning, check all endpoints for health issues and report any offline or compromised devices' },
      { name: 'Weekly Threat Summary', description: 'Friday EOD: compile all alerts from the week by type and severity, send to security leadership' },
      { name: 'Auto-Scan on Suspicious Activity', description: 'When a medium-risk alert fires, trigger a full scan on the affected endpoint automatically' },
    ],
  },
  'microsoft-defender': {
    chatPhrases: [
      'List active alerts in Microsoft Defender',
      'Show me all high severity alerts from today',
      'Isolate machine DESKTOP-ABC123',
      'Stop and quarantine file with SHA-1 hash abc123 on machine LAPTOP-XYZ',
      'List vulnerabilities across all machines — order by exposed machine count',
      'Create an indicator to block domain "phishing.example.com"',
      'List all active investigations in Defender',
      'Get all alerts for machine DESKTOP-ABC123',
      'Update alert ALR123 status to resolved with classification truePositive',
    ],
    automations: [
      { name: 'Defender → ServiceNow Pipeline', description: 'For each new high-severity Defender alert, automatically create a ServiceNow incident with full context' },
      { name: 'Daily Alert Briefing', description: 'Every morning, pull unresolved Defender alerts and post a prioritized list to #security-team in Slack' },
      { name: 'Machine Isolation Response', description: 'When a critical alert fires on a machine, isolate it immediately and page the on-call security engineer' },
      { name: 'Resolved Alert Cleanup', description: 'Weekly review of resolved alerts — generate a report for compliance documentation' },
    ],
  },
  'stellar-cyber': {
    chatPhrases: [
      'List active alerts in Stellar Cyber',
      'Show me open cases in Stellar Cyber',
      'What events match "lateral movement" in the last 24 hours?',
      'Create a new case for alert IDs 123 and 456',
      'Run a threat hunt with query "process_name: powershell AND parent: cmd" over the last 72 hours',
      'Add a comment to case 789: "Confirmed C2 traffic — escalating"',
      'List all sensors in Stellar Cyber',
      'Create an alert exception to suppress Lucene query: src_ip:192.168.1.100',
    ],
    automations: [
      { name: 'SIEM Alert Triage', description: 'Hourly: check for new high-confidence alerts, correlate with endpoint data, and escalate to PagerDuty if critical' },
      { name: 'Case to Ticket Bridge', description: 'When a new Stellar Cyber case is created, automatically open a corresponding ServiceNow ticket' },
      { name: 'Weekly Threat Hunt Report', description: 'Every Monday, run a search for common threat patterns from the past week and summarize findings' },
      { name: 'Cross-Platform Correlation', description: 'When Stellar Cyber detects suspicious lateral movement, cross-check with CrowdStrike endpoint data and alert the SOC' },
    ],
  },
  zendesk: {
    chatPhrases: [
      'List all open tickets in Zendesk',
      'Show me urgent priority tickets assigned to me',
      'Search Zendesk tickets for "payment error"',
      'Create a new Zendesk ticket: "Login broken for enterprise user", priority high',
      'Add a public comment to ticket #12345: "We\'re investigating this now"',
      'List all macros in Zendesk',
      'Apply macro "Close and thank" to ticket #12345',
      'Merge ticket #456 into ticket #123',
      'Suspend user user@example.com in Zendesk',
      'Get ticket metrics for ticket #12345',
    ],
    automations: [
      { name: 'Ticket Escalation Monitor', description: 'Every hour, check for tickets open longer than 4 hours without a reply — escalate to a senior agent and alert via Slack' },
      { name: 'Daily Ticket Health Report', description: 'Every morning, pull the count of open/pending/solved tickets and post a summary to #support-ops' },
      { name: 'VIP Customer Fast-Track', description: 'When a ticket comes in from a VIP customer domain, automatically set priority to urgent and assign to the senior queue' },
      { name: 'Weekly CSAT Analysis', description: 'Every Monday, compile CSAT scores from the previous week and identify the top 5 low-scoring tickets for review' },
    ],
  },
  plain: {
    chatPhrases: [
      'List open threads in Plain',
      'Search Plain threads for "billing"',
      'Find the customer with email user@example.com in Plain',
      'Create a new thread for customer@example.com titled "API rate limit issue"',
      'Reply to thread th_123: "We\'ve escalated this to our engineering team"',
      'Add an internal note to thread th_123 about the root cause',
      'Assign thread th_123 to user usr_456',
      'Set thread th_123 priority to urgent',
      'Add label "bug" to thread th_123',
      'Log a timeline event for customer@example.com: "User upgraded to Pro plan"',
    ],
    automations: [
      { name: 'Unanswered Thread Alert', description: 'Every 2 hours, check for threads with no response older than 3 hours and alert the support team in Slack' },
      { name: 'New Thread to Ticket', description: 'When a new Plain thread arrives from an enterprise customer, also create a tracking ticket in Zendesk or ServiceNow' },
      { name: 'Daily Support Digest', description: 'Every morning, summarize the previous day\'s threads: volume, resolution rate, top customer issues' },
      { name: 'Waiting → Follow Up', description: 'For threads marked "waiting on customer" over 48 hours, send an automated friendly follow-up and add a note' },
    ],
  },
  servicenow: {
    chatPhrases: [
      'List all open P1 incidents in ServiceNow',
      'Create a ServiceNow incident: "Production database down", priority 1',
      'Close incident INC0012345 with resolution "Root cause fixed — cache cleared"',
      'Add a work note to change request CHG001: "Testing completed successfully"',
      'Search the CMDB for servers with name "prod-web"',
      'List all open problem records',
      'List catalog items available for IT requests',
      'List all changes scheduled for this week',
    ],
    automations: [
      { name: 'P1 Incident War Room', description: 'When a P1 incident is created, immediately notify #incidents in Slack, page PagerDuty, and create a dedicated tracking thread' },
      { name: 'SLA Breach Warning', description: 'Check hourly for incidents approaching SLA breach (within 2 hours) and alert the assigned group' },
      { name: 'Daily Incident Report', description: 'Every morning, pull all open incidents by priority and send a status report to IT leadership' },
      { name: 'Auto-Resolve Stale', description: 'For incidents in Pending state with no update for 7 days, send a reminder to the assignee and flag for manager review' },
    ],
  },
  twilio: {
    chatPhrases: [
      'Send an SMS to +1-555-0100 saying "Your order is ready"',
      'Send an MMS to +1-555-0200 with image https://example.com/receipt.png',
      'Make a call to +1-555-0300 with TwiML: <Response><Say>This is an automated security alert.</Say></Response>',
      'Look up phone number +1-555-0100 to verify it\'s a mobile number',
      'Send a verification code to +1-555-0100 via the Verify service SID VA123',
      'Check verification: code 123456 for +1-555-0100',
      'List all phone numbers on my Twilio account',
      'Get the status of message SID SM123456',
      'Show Twilio usage for voice calls this month',
    ],
    automations: [
      { name: 'Critical Alert SMS', description: 'When a PagerDuty P1 fires, send an SMS to all on-call engineers with the incident title and link' },
      { name: 'Guest Check-In Notification', description: 'When a Lodgify reservation check-in date arrives, SMS the guest with door code and WiFi details' },
      { name: 'Two-Factor Confirmation', description: 'Before executing a destructive API action, SMS the admin a confirmation code via Twilio Verify' },
      { name: 'Weekly On-Call Reminder', description: 'SMS the upcoming on-call engineer every Sunday evening with their schedule for the week' },
    ],
  },
  sendgrid: {
    chatPhrases: [
      'Send an email to team@company.com with subject "Weekly Report"',
      'Send a templated email using template ID d-abc123 to john@example.com',
      'List all SendGrid templates',
      'Get email stats for the last 7 days',
      'List all bounced email addresses',
      'Delete bounce record for bounced@example.com',
      'List all contacts in SendGrid',
      'Add contacts to SendGrid: [{"email":"new@example.com","first_name":"Alice"}]',
      'Schedule a Single Send campaign to list abc123 at 2025-07-01T09:00:00Z',
    ],
    automations: [
      { name: 'Weekly Ops Report Email', description: 'Every Friday at 5 PM, generate a full ops report from your connected tools and email it to the leadership team' },
      { name: 'Alert Email on Failure', description: 'When any skill run fails 3+ times in a row, email the admin team with a full error summary' },
      { name: 'Connector Health Digest', description: 'Every Monday, email the workspace owner with a health check of all connected APIs' },
      { name: 'New Member Welcome', description: 'When a new member joins the workspace, send them a personalized welcome email with a quick-start guide' },
    ],
  },
  teams: {
    chatPhrases: [
      'Send a Teams message to the Security channel: "Incident detected"',
      'Post a facts card to Teams with title "Server Status" and facts {"Host":"prod-01","Status":"Down","Region":"us-east-1"}',
      'Post a table card to Teams Engineering channel: headers "Name,Status,Score", rows with 3 items',
      'Send an incident card to Teams: incident ID INC-001, title "DB Outage", severity critical',
      'Post a digest to Teams with 3 sections summarizing today\'s activity',
      'Send an image card to the team with our architecture diagram URL',
    ],
    automations: [
      { name: 'Incident Channel Notifications', description: 'When a P1 ServiceNow incident is created, post a severity-coded incident card to the Security Operations Teams channel' },
      { name: 'Daily Standup Post', description: 'Every morning, post a standup prompt card to the Engineering Teams channel' },
      { name: 'Deployment Status Updates', description: 'Post a Teams facts card when a deployment starts and another when it completes successfully or fails' },
      { name: 'On-Call Handoff Reminder', description: 'Every day at shift change, post the on-call schedule and any open incidents to the Ops Teams channel' },
    ],
  },
  netsuite: {
    chatPhrases: [
      'List all open invoices in NetSuite',
      'Run SuiteQL: SELECT TOP 10 id, tranid, entity FROM transaction WHERE type = \'Invoice\'',
      'List all vendors in NetSuite',
      'Show me purchase orders pending billing',
      'List open sales orders for customer "Acme Corp"',
      'Get transaction details for SO-1234',
      'List all employees in NetSuite',
      'Get the balance for GL account 1000',
      'List journal entries from this month',
      'List expense reports pending approval',
      'List inventory items matching "server"',
    ],
    automations: [
      { name: 'Weekly AP Review', description: 'Every Monday, pull all unpaid vendor bills due this week and email the AP team with a prioritized list' },
      { name: 'Large Invoice Alert', description: 'When a new invoice over $50,000 is created, notify the CFO and Finance Director via Slack for immediate review' },
      { name: 'Month-End Closing Checklist', description: 'On the last business day of each month, run a check for unposted transactions and alert the accounting team' },
      { name: 'Cash Flow Snapshot', description: 'Every morning, compile the current AR/AP position and send a cash flow summary to the finance leadership team' },
    ],
  },
  lodgify: {
    chatPhrases: [
      'List all reservations arriving this week',
      'What properties do I have in Lodgify?',
      'Show me availability for property 123 in July',
      'Get a price quote for property 123 from July 1–7 for 2 guests',
      'Block dates July 15–20 on room 456 for owner stay',
      'List all guests who stayed in the last 30 days',
      'Send an invoice to the guest on booking 789',
      'Update the nightly rate for room 456 to $250 for August',
      'List all rate plans for property 123',
      'Get revenue report for property 123 for Q2 2025',
    ],
    automations: [
      { name: 'Guest Arrival Workflow', description: 'Each morning, check today\'s arrivals and send each guest an SMS with check-in instructions, door code, and WiFi' },
      { name: 'Upcoming Week Briefing', description: 'Every Sunday, generate a summary of the week\'s arrivals, departures, and occupancy rate — send to your team' },
      { name: 'Checkout Reminder', description: 'At 9 AM on checkout day, send each departing guest a friendly reminder with checkout instructions' },
      { name: 'Low Availability Alert', description: 'When a property has fewer than 3 available nights in the next 30 days, send an email to review pricing' },
    ],
  },
  'eufy-security': {
    chatPhrases: [
      'List all my Eufy Security cameras and sensors',
      'Get the status of device SN T8600P1234567890',
      'List all security events from the last 6 hours',
      'Show me motion events for the Front Door camera today',
      'Set guard mode on my HomeBase to Away (mode 0)',
      'Trigger the alarm on HomeBase T8010P1234567890 for 30 seconds',
      'Disable motion detection on camera T8600P1234567890',
      'Set motion sensitivity to 3 on camera T8600P1234567890',
      'List all recorded clips from today',
      'Get the event thumbnail for event ev_001',
      'List users who have shared access to my Eufy account',
      'Reboot camera T8600P1234567890',
    ],
    automations: [
      { name: 'Motion → Alert', description: 'When motion is detected by any Eufy camera after hours, trigger the HomeBase alarm and send an SMS via Twilio' },
      { name: 'Guest Arrival Mode', description: 'When a Lodgify guest checks in, set guard mode to Home and disable motion detection on interior cameras' },
      { name: 'Nightly Security Arm', description: 'Every night at 10 PM, set all HomeBase stations to Away mode and send a confirmation to the owner via Slack' },
      { name: 'Morning Motion Summary', description: 'Every morning, pull all overnight motion and person-detected events and post a summary to the security team' },
    ],
  },
  'simulated-lights': {
    chatPhrases: [
      'List all my simulated lights',
      'Turn on the Living Room light',
      'Turn off all lights',
      'Set brightness of the Bedroom light to 50%',
      'Change the Entry light color to warm orange #FF8C00',
      'Activate the Relax scene on all devices',
      'Activate the Night scene on the Bedroom light',
      'Add a new light device called "Office"',
      'Toggle the Entry light',
      'Remove the unused "Old Lamp" device',
    ],
    automations: [
      { name: 'Guest Arrival Lights', description: 'When a Lodgify guest checks in, activate the "Entry" scene on all lights and send the guest a welcome message' },
      { name: 'Night Mode Schedule', description: 'Every night at 10 PM, activate the Night scene — dim red lights at 10% brightness across all devices' },
      { name: 'Doorbell Trigger', description: 'When the Simulated Ring doorbell fires, flash lights bright white for 3 seconds then restore the previous scene' },
      { name: 'Movie Mode', description: 'When asked to start movie mode, set all lights to 15% warm white, activate Relax scene, and confirm via chat' },
    ],
  },
  'simulated-ring': {
    chatPhrases: [
      'List all my Ring devices',
      'Show me the 10 most recent events',
      'Are there any unacknowledged motion events?',
      'Get an event summary for today',
      'Simulate a doorbell ring on Front Door',
      'Simulate person detected on Backyard Camera',
      'Acknowledge all pending events',
      'Add a camera device called "Backyard" at location "Pool Area"',
      'Clear all events for the Front Door device',
      'How many events of each type have been triggered today?',
    ],
    automations: [
      { name: 'Doorbell → Guest Welcome', description: 'When the Front Door doorbell rings, send the guest a Twilio SMS: "We see you! Check-in instructions sent to your email"' },
      { name: 'After-Hours Motion Alert', description: 'Between 10 PM and 6 AM, when motion is detected, send an immediate SMS and trigger the Simulated Lights alarm scene' },
      { name: 'Daily Event Digest', description: 'Every morning, get the event summary for the last 24 hours and post a breakdown to Slack #security channel' },
      { name: 'PagerDuty on Person Detected', description: 'When a person is detected at an unexpected time, open a PagerDuty incident for the security team to review' },
    ],
  },
}
