-- ============================================================
-- 014 — Conversation history (SUPERSEDED — intentionally a no-op)
-- ============================================================
-- This originally did `CREATE TABLE conversations`, but migration 001 had
-- already created that table. On the hosted database it therefore aborted
-- partway — and was still recorded as applied, which is how
-- `conversation_messages` came to be missing until migration 042 repaired it
-- (see the note at the top of 042).
--
-- That went unnoticed for a long time because the hosted database was built up
-- incrementally and never replayed from empty. The self-hosted edition DOES
-- replay from empty on every install, so the collision became a hard failure:
-- the app container crash-looped on
--     ✗ relation "conversations" already exists
-- and the stack never came up.
--
-- The correct end state is already produced by:
--   001  conversations
--   040  conversations.updated_at
--   042  conversation_messages, its index and its RLS policy
--
-- So there is nothing left for this migration to do.
--
-- Kept as a no-op rather than deleted: it is already recorded as applied on
-- the hosted database and every other existing environment, and removing the
-- file would make the migration list disagree with the tracking table.
--
-- The one thing 014 had that nothing else recreates is a trigger bumping
-- conversations.updated_at on insert. That omission is deliberate — the app
-- bumps it explicitly after each insert (see the note in 042).

select 1;   -- no-op
